; The installer's own texts, in each language it offers. The standard texts
; of the pages come from NSIS's language files.
;
; Each string is defined twice, as $(Name) for the installer and $(un.Name)
; for the uninstaller. $OldVer is the installed version, and the defines
; PRODUCT_NAME, VERSION and SERVICE_NAME come from the build.
;
; Keep the ids of installer.nsi in step: ReinstTitle, ReinstSubtitle,
; ReinstSame, ReinstOlder, ReinstUnknown, ReinstNewer, OptRepair,
; OptUninstall, OptUpgrade, OptDowngrade, OptClean, RunningMsg, CloseFailed,
; UninstallFailed, DesktopShortcut, DeleteData, ServiceAsk, ServiceLeft.

!macro LS lang id text
  LangString ${id} ${LANG_${lang}} "${text}"
  LangString un.${id} ${LANG_${lang}} "${text}"
!macroend

; ---- English ----
!insertmacro LS ENGLISH ReinstTitle "Already installed"
!insertmacro LS ENGLISH ReinstSubtitle "Choose how to proceed."
!insertmacro LS ENGLISH ReinstSame "${PRODUCT_NAME} $OldVer is already installed.$\r$\n$\r$\nWhat would you like to do?"
!insertmacro LS ENGLISH ReinstOlder "${PRODUCT_NAME} $OldVer is installed. Version ${VERSION} will update it.$\r$\n$\r$\nHow would you like to install?"
!insertmacro LS ENGLISH ReinstUnknown "An existing installation of ${PRODUCT_NAME} was found.$\r$\n$\r$\nHow would you like to install version ${VERSION}?"
!insertmacro LS ENGLISH ReinstNewer "A newer version of ${PRODUCT_NAME} ($OldVer) is installed. Installing version ${VERSION} is a downgrade, and settings saved by the newer version may not work with it.$\r$\n$\r$\nHow would you like to proceed?"
!insertmacro LS ENGLISH OptRepair "Repair / reinstall ${PRODUCT_NAME} (keeps your settings)"
!insertmacro LS ENGLISH OptUninstall "Uninstall ${PRODUCT_NAME}"
!insertmacro LS ENGLISH OptUpgrade "Upgrade to version ${VERSION} (recommended, keeps your settings)"
!insertmacro LS ENGLISH OptDowngrade "Downgrade to version ${VERSION} (keeps your settings)"
!insertmacro LS ENGLISH OptClean "Remove the old program files first, then install (keeps your settings)"
!insertmacro LS ENGLISH RunningMsg "${PRODUCT_NAME} is running. It must be closed, together with its core, to continue.$\r$\n$\r$\nClick OK to close it now, or Cancel to quit."
!insertmacro LS ENGLISH CloseFailed "${PRODUCT_NAME} could not be closed. Quit it from its tray icon, then click Retry."
!insertmacro LS ENGLISH UninstallFailed "The uninstaller of the existing installation could not be run."
!insertmacro LS ENGLISH DesktopShortcut "Create a desktop shortcut"
!insertmacro LS ENGLISH DeleteData "Also delete app data (settings, profiles, logs and cache)"
!insertmacro LS ENGLISH ServiceAsk "The ${PRODUCT_NAME} service (used by TUN mode) is installed. Removing it needs administrator permission.$\r$\n$\r$\nRemove it now?"
!insertmacro LS ENGLISH ServiceLeft "The service was not removed. To remove it later, run this in an administrator command prompt:$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- 简体中文 ----
!insertmacro LS SIMPCHINESE ReinstTitle "已安装"
!insertmacro LS SIMPCHINESE ReinstSubtitle "请选择安装方式。"
!insertmacro LS SIMPCHINESE ReinstSame "${PRODUCT_NAME} $OldVer 已安装。$\r$\n$\r$\n请选择要执行的操作。"
!insertmacro LS SIMPCHINESE ReinstOlder "已安装 ${PRODUCT_NAME} $OldVer，版本 ${VERSION} 将更新它。$\r$\n$\r$\n请选择安装方式。"
!insertmacro LS SIMPCHINESE ReinstUnknown "检测到已有的 ${PRODUCT_NAME} 安装。$\r$\n$\r$\n请选择安装版本 ${VERSION} 的方式。"
!insertmacro LS SIMPCHINESE ReinstNewer "已安装更新的 ${PRODUCT_NAME} ($OldVer)。安装版本 ${VERSION} 属于降级，新版本保存的设置可能无法在此版本中使用。$\r$\n$\r$\n请选择如何继续。"
!insertmacro LS SIMPCHINESE OptRepair "修复 / 重新安装 ${PRODUCT_NAME}（保留设置）"
!insertmacro LS SIMPCHINESE OptUninstall "卸载 ${PRODUCT_NAME}"
!insertmacro LS SIMPCHINESE OptUpgrade "升级到版本 ${VERSION}（推荐，保留设置）"
!insertmacro LS SIMPCHINESE OptDowngrade "降级到版本 ${VERSION}（保留设置）"
!insertmacro LS SIMPCHINESE OptClean "先删除旧的程序文件，再安装（保留设置）"
!insertmacro LS SIMPCHINESE RunningMsg "${PRODUCT_NAME} 正在运行，需要将它连同内核一起关闭才能继续。$\r$\n$\r$\n点击“确定”立即关闭，或点击“取消”退出。"
!insertmacro LS SIMPCHINESE CloseFailed "无法关闭 ${PRODUCT_NAME}。请从托盘图标退出它，然后点击“重试”。"
!insertmacro LS SIMPCHINESE UninstallFailed "无法运行现有安装的卸载程序。"
!insertmacro LS SIMPCHINESE DesktopShortcut "创建桌面快捷方式"
!insertmacro LS SIMPCHINESE DeleteData "同时删除应用数据（设置、配置文件、日志和缓存）"
!insertmacro LS SIMPCHINESE ServiceAsk "检测到已安装 ${PRODUCT_NAME} 服务（TUN 模式使用）。移除它需要管理员权限。$\r$\n$\r$\n现在移除吗？"
!insertmacro LS SIMPCHINESE ServiceLeft "服务未被移除。如需稍后移除，请在管理员命令提示符中运行：$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- 繁體中文 ----
!insertmacro LS TRADCHINESE ReinstTitle "已安裝"
!insertmacro LS TRADCHINESE ReinstSubtitle "請選擇安裝方式。"
!insertmacro LS TRADCHINESE ReinstSame "${PRODUCT_NAME} $OldVer 已安裝。$\r$\n$\r$\n請選擇要執行的操作。"
!insertmacro LS TRADCHINESE ReinstOlder "已安裝 ${PRODUCT_NAME} $OldVer，版本 ${VERSION} 將更新它。$\r$\n$\r$\n請選擇安裝方式。"
!insertmacro LS TRADCHINESE ReinstUnknown "偵測到既有的 ${PRODUCT_NAME} 安裝。$\r$\n$\r$\n請選擇安裝版本 ${VERSION} 的方式。"
!insertmacro LS TRADCHINESE ReinstNewer "已安裝較新的 ${PRODUCT_NAME} ($OldVer)。安裝版本 ${VERSION} 屬於降級，新版本儲存的設定可能無法在此版本中使用。$\r$\n$\r$\n請選擇如何繼續。"
!insertmacro LS TRADCHINESE OptRepair "修復 / 重新安裝 ${PRODUCT_NAME}（保留設定）"
!insertmacro LS TRADCHINESE OptUninstall "解除安裝 ${PRODUCT_NAME}"
!insertmacro LS TRADCHINESE OptUpgrade "升級到版本 ${VERSION}（建議，保留設定）"
!insertmacro LS TRADCHINESE OptDowngrade "降級到版本 ${VERSION}（保留設定）"
!insertmacro LS TRADCHINESE OptClean "先刪除舊的程式檔案，再安裝（保留設定）"
!insertmacro LS TRADCHINESE RunningMsg "${PRODUCT_NAME} 正在執行，需要將它連同核心一起關閉才能繼續。$\r$\n$\r$\n按「確定」立即關閉，或按「取消」結束。"
!insertmacro LS TRADCHINESE CloseFailed "無法關閉 ${PRODUCT_NAME}。請從系統匣圖示結束它，然後按「重試」。"
!insertmacro LS TRADCHINESE UninstallFailed "無法執行既有安裝的解除安裝程式。"
!insertmacro LS TRADCHINESE DesktopShortcut "建立桌面捷徑"
!insertmacro LS TRADCHINESE DeleteData "同時刪除應用程式資料（設定、設定檔、記錄與快取）"
!insertmacro LS TRADCHINESE ServiceAsk "偵測到已安裝 ${PRODUCT_NAME} 服務（TUN 模式使用）。移除它需要系統管理員權限。$\r$\n$\r$\n要現在移除嗎？"
!insertmacro LS TRADCHINESE ServiceLeft "服務未被移除。若要稍後移除，請在系統管理員命令提示字元中執行：$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- 日本語 ----
!insertmacro LS JAPANESE ReinstTitle "インストール済み"
!insertmacro LS JAPANESE ReinstSubtitle "続行する方法を選択してください。"
!insertmacro LS JAPANESE ReinstSame "${PRODUCT_NAME} $OldVer は既にインストールされています。$\r$\n$\r$\n実行する操作を選択してください。"
!insertmacro LS JAPANESE ReinstOlder "${PRODUCT_NAME} $OldVer がインストールされています。バージョン ${VERSION} で更新されます。$\r$\n$\r$\nインストール方法を選択してください。"
!insertmacro LS JAPANESE ReinstUnknown "既存の ${PRODUCT_NAME} が見つかりました。$\r$\n$\r$\nバージョン ${VERSION} のインストール方法を選択してください。"
!insertmacro LS JAPANESE ReinstNewer "より新しい ${PRODUCT_NAME} ($OldVer) がインストールされています。バージョン ${VERSION} のインストールはダウングレードとなり、新しいバージョンで保存された設定は使えない場合があります。$\r$\n$\r$\n続行方法を選択してください。"
!insertmacro LS JAPANESE OptRepair "${PRODUCT_NAME} を修復 / 再インストールする（設定は保持）"
!insertmacro LS JAPANESE OptUninstall "${PRODUCT_NAME} をアンインストールする"
!insertmacro LS JAPANESE OptUpgrade "バージョン ${VERSION} にアップグレードする（推奨、設定は保持）"
!insertmacro LS JAPANESE OptDowngrade "バージョン ${VERSION} にダウングレードする（設定は保持）"
!insertmacro LS JAPANESE OptClean "古いプログラムファイルを先に削除してからインストールする（設定は保持）"
!insertmacro LS JAPANESE RunningMsg "${PRODUCT_NAME} が実行中です。続行するには、コアも含めて終了する必要があります。$\r$\n$\r$\n今すぐ終了するには [OK]、中止するには [キャンセル] をクリックしてください。"
!insertmacro LS JAPANESE CloseFailed "${PRODUCT_NAME} を終了できませんでした。トレイアイコンから終了し、[再試行] をクリックしてください。"
!insertmacro LS JAPANESE UninstallFailed "既存のインストールのアンインストーラーを実行できませんでした。"
!insertmacro LS JAPANESE DesktopShortcut "デスクトップにショートカットを作成する"
!insertmacro LS JAPANESE DeleteData "アプリのデータ（設定、プロファイル、ログ、キャッシュ）も削除する"
!insertmacro LS JAPANESE ServiceAsk "${PRODUCT_NAME} サービス（TUN モードで使用）がインストールされています。削除には管理者権限が必要です。$\r$\n$\r$\n今すぐ削除しますか？"
!insertmacro LS JAPANESE ServiceLeft "サービスは削除されませんでした。後で削除するには、管理者のコマンドプロンプトで次を実行してください：$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- 한국어 ----
!insertmacro LS KOREAN ReinstTitle "이미 설치됨"
!insertmacro LS KOREAN ReinstSubtitle "진행 방법을 선택하세요."
!insertmacro LS KOREAN ReinstSame "${PRODUCT_NAME} $OldVer 이(가) 이미 설치되어 있습니다.$\r$\n$\r$\n수행할 작업을 선택하세요."
!insertmacro LS KOREAN ReinstOlder "${PRODUCT_NAME} $OldVer 이(가) 설치되어 있습니다. 버전 ${VERSION}(으)로 업데이트됩니다.$\r$\n$\r$\n설치 방법을 선택하세요."
!insertmacro LS KOREAN ReinstUnknown "기존 ${PRODUCT_NAME} 설치가 발견되었습니다.$\r$\n$\r$\n버전 ${VERSION} 설치 방법을 선택하세요."
!insertmacro LS KOREAN ReinstNewer "더 최신 버전의 ${PRODUCT_NAME} ($OldVer)이(가) 설치되어 있습니다. 버전 ${VERSION} 설치는 다운그레이드이며, 최신 버전에서 저장한 설정은 이 버전에서 작동하지 않을 수 있습니다.$\r$\n$\r$\n진행 방법을 선택하세요."
!insertmacro LS KOREAN OptRepair "${PRODUCT_NAME} 복구 / 다시 설치 (설정 유지)"
!insertmacro LS KOREAN OptUninstall "${PRODUCT_NAME} 제거"
!insertmacro LS KOREAN OptUpgrade "버전 ${VERSION}(으)로 업그레이드 (권장, 설정 유지)"
!insertmacro LS KOREAN OptDowngrade "버전 ${VERSION}(으)로 다운그레이드 (설정 유지)"
!insertmacro LS KOREAN OptClean "이전 프로그램 파일을 먼저 삭제한 후 설치 (설정 유지)"
!insertmacro LS KOREAN RunningMsg "${PRODUCT_NAME} 이(가) 실행 중입니다. 계속하려면 코어와 함께 종료해야 합니다.$\r$\n$\r$\n지금 종료하려면 [확인]을, 중단하려면 [취소]를 클릭하세요."
!insertmacro LS KOREAN CloseFailed "${PRODUCT_NAME} 을(를) 종료할 수 없습니다. 트레이 아이콘에서 종료한 후 [다시 시도]를 클릭하세요."
!insertmacro LS KOREAN UninstallFailed "기존 설치의 제거 프로그램을 실행할 수 없습니다."
!insertmacro LS KOREAN DesktopShortcut "바탕 화면 바로 가기 만들기"
!insertmacro LS KOREAN DeleteData "앱 데이터(설정, 프로필, 로그, 캐시)도 삭제"
!insertmacro LS KOREAN ServiceAsk "${PRODUCT_NAME} 서비스(TUN 모드에서 사용)가 설치되어 있습니다. 제거하려면 관리자 권한이 필요합니다.$\r$\n$\r$\n지금 제거하시겠습니까?"
!insertmacro LS KOREAN ServiceLeft "서비스가 제거되지 않았습니다. 나중에 제거하려면 관리자 명령 프롬프트에서 다음을 실행하세요:$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- Русский ----
!insertmacro LS RUSSIAN ReinstTitle "Уже установлено"
!insertmacro LS RUSSIAN ReinstSubtitle "Выберите, как продолжить."
!insertmacro LS RUSSIAN ReinstSame "${PRODUCT_NAME} $OldVer уже установлен.$\r$\n$\r$\nЧто вы хотите сделать?"
!insertmacro LS RUSSIAN ReinstOlder "Установлен ${PRODUCT_NAME} $OldVer. Версия ${VERSION} обновит его.$\r$\n$\r$\nКак выполнить установку?"
!insertmacro LS RUSSIAN ReinstUnknown "Обнаружена существующая установка ${PRODUCT_NAME}.$\r$\n$\r$\nКак установить версию ${VERSION}?"
!insertmacro LS RUSSIAN ReinstNewer "Установлена более новая версия ${PRODUCT_NAME} ($OldVer). Установка версии ${VERSION} является понижением версии, а настройки, сохранённые новой версией, могут не работать в ней.$\r$\n$\r$\nКак продолжить?"
!insertmacro LS RUSSIAN OptRepair "Восстановить / переустановить ${PRODUCT_NAME} (настройки сохранятся)"
!insertmacro LS RUSSIAN OptUninstall "Удалить ${PRODUCT_NAME}"
!insertmacro LS RUSSIAN OptUpgrade "Обновить до версии ${VERSION} (рекомендуется, настройки сохранятся)"
!insertmacro LS RUSSIAN OptDowngrade "Понизить до версии ${VERSION} (настройки сохранятся)"
!insertmacro LS RUSSIAN OptClean "Сначала удалить старые файлы программы, затем установить (настройки сохранятся)"
!insertmacro LS RUSSIAN RunningMsg "${PRODUCT_NAME} запущен. Чтобы продолжить, его нужно закрыть вместе с ядром.$\r$\n$\r$\nНажмите «OK», чтобы закрыть его сейчас, или «Отмена», чтобы выйти."
!insertmacro LS RUSSIAN CloseFailed "Не удалось закрыть ${PRODUCT_NAME}. Выйдите из него через значок в трее и нажмите «Повторить»."
!insertmacro LS RUSSIAN UninstallFailed "Не удалось запустить программу удаления существующей установки."
!insertmacro LS RUSSIAN DesktopShortcut "Создать ярлык на рабочем столе"
!insertmacro LS RUSSIAN DeleteData "Также удалить данные приложения (настройки, профили, журналы и кэш)"
!insertmacro LS RUSSIAN ServiceAsk "Установлена служба ${PRODUCT_NAME} (используется режимом TUN). Для её удаления нужны права администратора.$\r$\n$\r$\nУдалить её сейчас?"
!insertmacro LS RUSSIAN ServiceLeft "Служба не была удалена. Чтобы удалить её позже, выполните в командной строке администратора:$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- Deutsch ----
!insertmacro LS GERMAN ReinstTitle "Bereits installiert"
!insertmacro LS GERMAN ReinstSubtitle "Wählen Sie, wie es weitergehen soll."
!insertmacro LS GERMAN ReinstSame "${PRODUCT_NAME} $OldVer ist bereits installiert.$\r$\n$\r$\nWas möchten Sie tun?"
!insertmacro LS GERMAN ReinstOlder "${PRODUCT_NAME} $OldVer ist installiert. Version ${VERSION} aktualisiert sie.$\r$\n$\r$\nWie möchten Sie installieren?"
!insertmacro LS GERMAN ReinstUnknown "Eine vorhandene Installation von ${PRODUCT_NAME} wurde gefunden.$\r$\n$\r$\nWie möchten Sie Version ${VERSION} installieren?"
!insertmacro LS GERMAN ReinstNewer "Eine neuere Version von ${PRODUCT_NAME} ($OldVer) ist installiert. Die Installation von Version ${VERSION} ist ein Downgrade, und Einstellungen der neueren Version funktionieren damit möglicherweise nicht.$\r$\n$\r$\nWie möchten Sie fortfahren?"
!insertmacro LS GERMAN OptRepair "${PRODUCT_NAME} reparieren / neu installieren (Einstellungen bleiben erhalten)"
!insertmacro LS GERMAN OptUninstall "${PRODUCT_NAME} deinstallieren"
!insertmacro LS GERMAN OptUpgrade "Auf Version ${VERSION} aktualisieren (empfohlen, Einstellungen bleiben erhalten)"
!insertmacro LS GERMAN OptDowngrade "Auf Version ${VERSION} zurückstufen (Einstellungen bleiben erhalten)"
!insertmacro LS GERMAN OptClean "Zuerst die alten Programmdateien entfernen, dann installieren (Einstellungen bleiben erhalten)"
!insertmacro LS GERMAN RunningMsg "${PRODUCT_NAME} läuft. Zum Fortfahren muss es samt Kern beendet werden.$\r$\n$\r$\nKlicken Sie auf OK, um es jetzt zu beenden, oder auf Abbrechen, um zu schließen."
!insertmacro LS GERMAN CloseFailed "${PRODUCT_NAME} konnte nicht beendet werden. Beenden Sie es über das Symbol im Infobereich und klicken Sie dann auf Wiederholen."
!insertmacro LS GERMAN UninstallFailed "Das Deinstallationsprogramm der vorhandenen Installation konnte nicht gestartet werden."
!insertmacro LS GERMAN DesktopShortcut "Desktopverknüpfung erstellen"
!insertmacro LS GERMAN DeleteData "Auch App-Daten löschen (Einstellungen, Profile, Protokolle und Cache)"
!insertmacro LS GERMAN ServiceAsk "Der Dienst von ${PRODUCT_NAME} (für den TUN-Modus) ist installiert. Zum Entfernen sind Administratorrechte nötig.$\r$\n$\r$\nJetzt entfernen?"
!insertmacro LS GERMAN ServiceLeft "Der Dienst wurde nicht entfernt. Um ihn später zu entfernen, führen Sie in einer Eingabeaufforderung als Administrator Folgendes aus:$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- Français ----
!insertmacro LS FRENCH ReinstTitle "Déjà installé"
!insertmacro LS FRENCH ReinstSubtitle "Choisissez comment poursuivre."
!insertmacro LS FRENCH ReinstSame "${PRODUCT_NAME} $OldVer est déjà installé.$\r$\n$\r$\nQue souhaitez-vous faire ?"
!insertmacro LS FRENCH ReinstOlder "${PRODUCT_NAME} $OldVer est installé. La version ${VERSION} le mettra à jour.$\r$\n$\r$\nComment souhaitez-vous installer ?"
!insertmacro LS FRENCH ReinstUnknown "Une installation existante de ${PRODUCT_NAME} a été trouvée.$\r$\n$\r$\nComment souhaitez-vous installer la version ${VERSION} ?"
!insertmacro LS FRENCH ReinstNewer "Une version plus récente de ${PRODUCT_NAME} ($OldVer) est installée. Installer la version ${VERSION} est une rétrogradation, et les réglages enregistrés par la version récente peuvent ne pas fonctionner avec elle.$\r$\n$\r$\nComment souhaitez-vous poursuivre ?"
!insertmacro LS FRENCH OptRepair "Réparer / réinstaller ${PRODUCT_NAME} (conserve vos réglages)"
!insertmacro LS FRENCH OptUninstall "Désinstaller ${PRODUCT_NAME}"
!insertmacro LS FRENCH OptUpgrade "Mettre à jour vers la version ${VERSION} (recommandé, conserve vos réglages)"
!insertmacro LS FRENCH OptDowngrade "Rétrograder vers la version ${VERSION} (conserve vos réglages)"
!insertmacro LS FRENCH OptClean "Supprimer d’abord les anciens fichiers du programme, puis installer (conserve vos réglages)"
!insertmacro LS FRENCH RunningMsg "${PRODUCT_NAME} est en cours d’exécution. Il doit être fermé, avec son noyau, pour continuer.$\r$\n$\r$\nCliquez sur OK pour le fermer maintenant, ou sur Annuler pour quitter."
!insertmacro LS FRENCH CloseFailed "${PRODUCT_NAME} n’a pas pu être fermé. Quittez-le depuis son icône de la zone de notification, puis cliquez sur Réessayer."
!insertmacro LS FRENCH UninstallFailed "Le désinstallateur de l’installation existante n’a pas pu être lancé."
!insertmacro LS FRENCH DesktopShortcut "Créer un raccourci sur le bureau"
!insertmacro LS FRENCH DeleteData "Supprimer aussi les données de l’app (réglages, profils, journaux et cache)"
!insertmacro LS FRENCH ServiceAsk "Le service ${PRODUCT_NAME} (utilisé par le mode TUN) est installé. Pour le supprimer, il faut les droits d’administrateur.$\r$\n$\r$\nLe supprimer maintenant ?"
!insertmacro LS FRENCH ServiceLeft "Le service n’a pas été supprimé. Pour le supprimer plus tard, exécutez ceci dans une invite de commandes administrateur :$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- Español ----
!insertmacro LS SPANISH ReinstTitle "Ya instalado"
!insertmacro LS SPANISH ReinstSubtitle "Elige cómo continuar."
!insertmacro LS SPANISH ReinstSame "${PRODUCT_NAME} $OldVer ya está instalado.$\r$\n$\r$\n¿Qué quieres hacer?"
!insertmacro LS SPANISH ReinstOlder "${PRODUCT_NAME} $OldVer está instalado. La versión ${VERSION} lo actualizará.$\r$\n$\r$\n¿Cómo quieres instalar?"
!insertmacro LS SPANISH ReinstUnknown "Se encontró una instalación existente de ${PRODUCT_NAME}.$\r$\n$\r$\n¿Cómo quieres instalar la versión ${VERSION}?"
!insertmacro LS SPANISH ReinstNewer "Hay instalada una versión más reciente de ${PRODUCT_NAME} ($OldVer). Instalar la versión ${VERSION} es una degradación, y los ajustes guardados por la versión más reciente pueden no funcionar con ella.$\r$\n$\r$\n¿Cómo quieres continuar?"
!insertmacro LS SPANISH OptRepair "Reparar / reinstalar ${PRODUCT_NAME} (conserva tus ajustes)"
!insertmacro LS SPANISH OptUninstall "Desinstalar ${PRODUCT_NAME}"
!insertmacro LS SPANISH OptUpgrade "Actualizar a la versión ${VERSION} (recomendado, conserva tus ajustes)"
!insertmacro LS SPANISH OptDowngrade "Degradar a la versión ${VERSION} (conserva tus ajustes)"
!insertmacro LS SPANISH OptClean "Eliminar primero los archivos antiguos del programa y luego instalar (conserva tus ajustes)"
!insertmacro LS SPANISH RunningMsg "${PRODUCT_NAME} se está ejecutando. Hay que cerrarlo, junto con su núcleo, para continuar.$\r$\n$\r$\nHaz clic en Aceptar para cerrarlo ahora o en Cancelar para salir."
!insertmacro LS SPANISH CloseFailed "No se pudo cerrar ${PRODUCT_NAME}. Sal de la app desde su icono de la bandeja y haz clic en Reintentar."
!insertmacro LS SPANISH UninstallFailed "No se pudo ejecutar el desinstalador de la instalación existente."
!insertmacro LS SPANISH DesktopShortcut "Crear un acceso directo en el escritorio"
!insertmacro LS SPANISH DeleteData "Eliminar también los datos de la app (ajustes, perfiles, registros y caché)"
!insertmacro LS SPANISH ServiceAsk "El servicio de ${PRODUCT_NAME} (usado por el modo TUN) está instalado. Para quitarlo se necesitan permisos de administrador.$\r$\n$\r$\n¿Quitarlo ahora?"
!insertmacro LS SPANISH ServiceLeft "No se quitó el servicio. Para quitarlo más tarde, ejecuta esto en un símbolo del sistema como administrador:$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- Português (Brasil) ----
!insertmacro LS PORTUGUESEBR ReinstTitle "Já instalado"
!insertmacro LS PORTUGUESEBR ReinstSubtitle "Escolha como prosseguir."
!insertmacro LS PORTUGUESEBR ReinstSame "O ${PRODUCT_NAME} $OldVer já está instalado.$\r$\n$\r$\nO que você deseja fazer?"
!insertmacro LS PORTUGUESEBR ReinstOlder "O ${PRODUCT_NAME} $OldVer está instalado. A versão ${VERSION} irá atualizá-lo.$\r$\n$\r$\nComo você deseja instalar?"
!insertmacro LS PORTUGUESEBR ReinstUnknown "Foi encontrada uma instalação existente do ${PRODUCT_NAME}.$\r$\n$\r$\nComo você deseja instalar a versão ${VERSION}?"
!insertmacro LS PORTUGUESEBR ReinstNewer "Uma versão mais recente do ${PRODUCT_NAME} ($OldVer) está instalada. Instalar a versão ${VERSION} é um downgrade, e as configurações salvas pela versão mais recente podem não funcionar nela.$\r$\n$\r$\nComo você deseja prosseguir?"
!insertmacro LS PORTUGUESEBR OptRepair "Reparar / reinstalar o ${PRODUCT_NAME} (mantém suas configurações)"
!insertmacro LS PORTUGUESEBR OptUninstall "Desinstalar o ${PRODUCT_NAME}"
!insertmacro LS PORTUGUESEBR OptUpgrade "Atualizar para a versão ${VERSION} (recomendado, mantém suas configurações)"
!insertmacro LS PORTUGUESEBR OptDowngrade "Voltar para a versão ${VERSION} (mantém suas configurações)"
!insertmacro LS PORTUGUESEBR OptClean "Remover primeiro os arquivos antigos do programa e depois instalar (mantém suas configurações)"
!insertmacro LS PORTUGUESEBR RunningMsg "O ${PRODUCT_NAME} está em execução. Ele precisa ser fechado, junto com seu núcleo, para continuar.$\r$\n$\r$\nClique em OK para fechá-lo agora ou em Cancelar para sair."
!insertmacro LS PORTUGUESEBR CloseFailed "Não foi possível fechar o ${PRODUCT_NAME}. Saia dele pelo ícone da bandeja e clique em Tentar novamente."
!insertmacro LS PORTUGUESEBR UninstallFailed "Não foi possível executar o desinstalador da instalação existente."
!insertmacro LS PORTUGUESEBR DesktopShortcut "Criar um atalho na área de trabalho"
!insertmacro LS PORTUGUESEBR DeleteData "Excluir também os dados do app (configurações, perfis, logs e cache)"
!insertmacro LS PORTUGUESEBR ServiceAsk "O serviço do ${PRODUCT_NAME} (usado pelo modo TUN) está instalado. Removê-lo exige permissão de administrador.$\r$\n$\r$\nRemover agora?"
!insertmacro LS PORTUGUESEBR ServiceLeft "O serviço não foi removido. Para removê-lo depois, execute isto em um prompt de comando como administrador:$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- Italiano ----
!insertmacro LS ITALIAN ReinstTitle "Già installato"
!insertmacro LS ITALIAN ReinstSubtitle "Scegli come procedere."
!insertmacro LS ITALIAN ReinstSame "${PRODUCT_NAME} $OldVer è già installato.$\r$\n$\r$\nCosa vuoi fare?"
!insertmacro LS ITALIAN ReinstOlder "${PRODUCT_NAME} $OldVer è installato. La versione ${VERSION} lo aggiornerà.$\r$\n$\r$\nCome vuoi installare?"
!insertmacro LS ITALIAN ReinstUnknown "È stata trovata un’installazione esistente di ${PRODUCT_NAME}.$\r$\n$\r$\nCome vuoi installare la versione ${VERSION}?"
!insertmacro LS ITALIAN ReinstNewer "È installata una versione più recente di ${PRODUCT_NAME} ($OldVer). Installare la versione ${VERSION} è un downgrade e le impostazioni salvate dalla versione più recente potrebbero non funzionare.$\r$\n$\r$\nCome vuoi procedere?"
!insertmacro LS ITALIAN OptRepair "Ripara / reinstalla ${PRODUCT_NAME} (mantiene le impostazioni)"
!insertmacro LS ITALIAN OptUninstall "Disinstalla ${PRODUCT_NAME}"
!insertmacro LS ITALIAN OptUpgrade "Aggiorna alla versione ${VERSION} (consigliato, mantiene le impostazioni)"
!insertmacro LS ITALIAN OptDowngrade "Torna alla versione ${VERSION} (mantiene le impostazioni)"
!insertmacro LS ITALIAN OptClean "Rimuovi prima i vecchi file del programma, poi installa (mantiene le impostazioni)"
!insertmacro LS ITALIAN RunningMsg "${PRODUCT_NAME} è in esecuzione. Per continuare va chiuso, insieme al suo core.$\r$\n$\r$\nFai clic su OK per chiuderlo ora o su Annulla per uscire."
!insertmacro LS ITALIAN CloseFailed "Impossibile chiudere ${PRODUCT_NAME}. Esci dall’app dall’icona nell’area di notifica, quindi fai clic su Riprova."
!insertmacro LS ITALIAN UninstallFailed "Impossibile eseguire il programma di disinstallazione dell’installazione esistente."
!insertmacro LS ITALIAN DesktopShortcut "Crea un collegamento sul desktop"
!insertmacro LS ITALIAN DeleteData "Elimina anche i dati dell’app (impostazioni, profili, log e cache)"
!insertmacro LS ITALIAN ServiceAsk "Il servizio di ${PRODUCT_NAME} (usato dalla modalità TUN) è installato. Rimuoverlo richiede i permessi di amministratore.$\r$\n$\r$\nRimuoverlo ora?"
!insertmacro LS ITALIAN ServiceLeft "Il servizio non è stato rimosso. Per rimuoverlo in seguito, esegui questo in un prompt dei comandi come amministratore:$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- Türkçe ----
!insertmacro LS TURKISH ReinstTitle "Zaten yüklü"
!insertmacro LS TURKISH ReinstSubtitle "Nasıl devam edileceğini seçin."
!insertmacro LS TURKISH ReinstSame "${PRODUCT_NAME} $OldVer zaten yüklü.$\r$\n$\r$\nNe yapmak istersiniz?"
!insertmacro LS TURKISH ReinstOlder "${PRODUCT_NAME} $OldVer yüklü. ${VERSION} sürümü onu güncelleyecek.$\r$\n$\r$\nNasıl yüklemek istersiniz?"
!insertmacro LS TURKISH ReinstUnknown "Mevcut bir ${PRODUCT_NAME} kurulumu bulundu.$\r$\n$\r$\n${VERSION} sürümünü nasıl yüklemek istersiniz?"
!insertmacro LS TURKISH ReinstNewer "${PRODUCT_NAME} uygulamasının daha yeni bir sürümü ($OldVer) yüklü. ${VERSION} sürümünü yüklemek sürüm düşürmedir ve yeni sürümün kaydettiği ayarlar bu sürümde çalışmayabilir.$\r$\n$\r$\nNasıl devam etmek istersiniz?"
!insertmacro LS TURKISH OptRepair "${PRODUCT_NAME} uygulamasını onar / yeniden yükle (ayarlarınız korunur)"
!insertmacro LS TURKISH OptUninstall "${PRODUCT_NAME} uygulamasını kaldır"
!insertmacro LS TURKISH OptUpgrade "${VERSION} sürümüne yükselt (önerilir, ayarlarınız korunur)"
!insertmacro LS TURKISH OptDowngrade "${VERSION} sürümüne düşür (ayarlarınız korunur)"
!insertmacro LS TURKISH OptClean "Önce eski program dosyalarını sil, sonra yükle (ayarlarınız korunur)"
!insertmacro LS TURKISH RunningMsg "${PRODUCT_NAME} çalışıyor. Devam etmek için çekirdeğiyle birlikte kapatılması gerekiyor.$\r$\n$\r$\nŞimdi kapatmak için Tamam'a, çıkmak için İptal'e tıklayın."
!insertmacro LS TURKISH CloseFailed "${PRODUCT_NAME} kapatılamadı. Uygulamadan bildirim alanı simgesiyle çıkın, ardından Yeniden Dene'ye tıklayın."
!insertmacro LS TURKISH UninstallFailed "Mevcut kurulumun kaldırma programı çalıştırılamadı."
!insertmacro LS TURKISH DesktopShortcut "Masaüstü kısayolu oluştur"
!insertmacro LS TURKISH DeleteData "Uygulama verilerini de sil (ayarlar, profiller, günlükler ve önbellek)"
!insertmacro LS TURKISH ServiceAsk "${PRODUCT_NAME} hizmeti (TUN modu tarafından kullanılır) yüklü. Kaldırmak için yönetici izni gerekir.$\r$\n$\r$\nŞimdi kaldırılsın mı?"
!insertmacro LS TURKISH ServiceLeft "Hizmet kaldırılmadı. Daha sonra kaldırmak için yönetici olarak açılmış bir komut isteminde şunu çalıştırın:$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- Tiếng Việt ----
!insertmacro LS VIETNAMESE ReinstTitle "Đã được cài đặt"
!insertmacro LS VIETNAMESE ReinstSubtitle "Chọn cách tiếp tục."
!insertmacro LS VIETNAMESE ReinstSame "${PRODUCT_NAME} $OldVer đã được cài đặt.$\r$\n$\r$\nBạn muốn làm gì?"
!insertmacro LS VIETNAMESE ReinstOlder "${PRODUCT_NAME} $OldVer đang được cài đặt. Phiên bản ${VERSION} sẽ cập nhật nó.$\r$\n$\r$\nBạn muốn cài đặt như thế nào?"
!insertmacro LS VIETNAMESE ReinstUnknown "Đã tìm thấy một bản cài đặt ${PRODUCT_NAME} hiện có.$\r$\n$\r$\nBạn muốn cài đặt phiên bản ${VERSION} như thế nào?"
!insertmacro LS VIETNAMESE ReinstNewer "Một phiên bản ${PRODUCT_NAME} mới hơn ($OldVer) đang được cài đặt. Cài phiên bản ${VERSION} là hạ cấp, và các thiết lập do phiên bản mới lưu có thể không dùng được.$\r$\n$\r$\nBạn muốn tiếp tục như thế nào?"
!insertmacro LS VIETNAMESE OptRepair "Sửa chữa / cài đặt lại ${PRODUCT_NAME} (giữ nguyên thiết lập)"
!insertmacro LS VIETNAMESE OptUninstall "Gỡ cài đặt ${PRODUCT_NAME}"
!insertmacro LS VIETNAMESE OptUpgrade "Nâng cấp lên phiên bản ${VERSION} (khuyến nghị, giữ nguyên thiết lập)"
!insertmacro LS VIETNAMESE OptDowngrade "Hạ cấp xuống phiên bản ${VERSION} (giữ nguyên thiết lập)"
!insertmacro LS VIETNAMESE OptClean "Xóa các tệp chương trình cũ trước, rồi cài đặt (giữ nguyên thiết lập)"
!insertmacro LS VIETNAMESE RunningMsg "${PRODUCT_NAME} đang chạy. Cần đóng nó cùng với lõi của nó để tiếp tục.$\r$\n$\r$\nNhấn OK để đóng ngay, hoặc Cancel để thoát."
!insertmacro LS VIETNAMESE CloseFailed "Không thể đóng ${PRODUCT_NAME}. Hãy thoát ứng dụng từ biểu tượng ở khay hệ thống, rồi nhấn Retry."
!insertmacro LS VIETNAMESE UninstallFailed "Không thể chạy trình gỡ cài đặt của bản cài đặt hiện có."
!insertmacro LS VIETNAMESE DesktopShortcut "Tạo lối tắt trên màn hình nền"
!insertmacro LS VIETNAMESE DeleteData "Xóa cả dữ liệu ứng dụng (thiết lập, hồ sơ, nhật ký và bộ nhớ đệm)"
!insertmacro LS VIETNAMESE ServiceAsk "Dịch vụ ${PRODUCT_NAME} (dùng cho chế độ TUN) đang được cài đặt. Gỡ bỏ nó cần quyền quản trị viên.$\r$\n$\r$\nGỡ bỏ ngay bây giờ?"
!insertmacro LS VIETNAMESE ServiceLeft "Dịch vụ chưa được gỡ bỏ. Để gỡ sau, hãy chạy lệnh sau trong Command Prompt với quyền quản trị viên:$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- Bahasa Indonesia ----
!insertmacro LS INDONESIAN ReinstTitle "Sudah terpasang"
!insertmacro LS INDONESIAN ReinstSubtitle "Pilih cara melanjutkan."
!insertmacro LS INDONESIAN ReinstSame "${PRODUCT_NAME} $OldVer sudah terpasang.$\r$\n$\r$\nApa yang ingin Anda lakukan?"
!insertmacro LS INDONESIAN ReinstOlder "${PRODUCT_NAME} $OldVer terpasang. Versi ${VERSION} akan memperbaruinya.$\r$\n$\r$\nBagaimana Anda ingin memasang?"
!insertmacro LS INDONESIAN ReinstUnknown "Ditemukan pemasangan ${PRODUCT_NAME} yang sudah ada.$\r$\n$\r$\nBagaimana Anda ingin memasang versi ${VERSION}?"
!insertmacro LS INDONESIAN ReinstNewer "Versi ${PRODUCT_NAME} yang lebih baru ($OldVer) terpasang. Memasang versi ${VERSION} berarti menurunkan versi, dan pengaturan yang disimpan versi baru mungkin tidak berfungsi.$\r$\n$\r$\nBagaimana Anda ingin melanjutkan?"
!insertmacro LS INDONESIAN OptRepair "Perbaiki / pasang ulang ${PRODUCT_NAME} (pengaturan tetap tersimpan)"
!insertmacro LS INDONESIAN OptUninstall "Copot ${PRODUCT_NAME}"
!insertmacro LS INDONESIAN OptUpgrade "Tingkatkan ke versi ${VERSION} (disarankan, pengaturan tetap tersimpan)"
!insertmacro LS INDONESIAN OptDowngrade "Turunkan ke versi ${VERSION} (pengaturan tetap tersimpan)"
!insertmacro LS INDONESIAN OptClean "Hapus dulu berkas program lama, lalu pasang (pengaturan tetap tersimpan)"
!insertmacro LS INDONESIAN RunningMsg "${PRODUCT_NAME} sedang berjalan. Aplikasi harus ditutup bersama intinya untuk melanjutkan.$\r$\n$\r$\nKlik OK untuk menutupnya sekarang, atau Cancel untuk keluar."
!insertmacro LS INDONESIAN CloseFailed "${PRODUCT_NAME} tidak dapat ditutup. Keluar dari aplikasi lewat ikon baki, lalu klik Retry."
!insertmacro LS INDONESIAN UninstallFailed "Program pencopot pemasangan yang ada tidak dapat dijalankan."
!insertmacro LS INDONESIAN DesktopShortcut "Buat pintasan desktop"
!insertmacro LS INDONESIAN DeleteData "Hapus juga data aplikasi (pengaturan, profil, log, dan cache)"
!insertmacro LS INDONESIAN ServiceAsk "Layanan ${PRODUCT_NAME} (dipakai mode TUN) terpasang. Menghapusnya memerlukan izin administrator.$\r$\n$\r$\nHapus sekarang?"
!insertmacro LS INDONESIAN ServiceLeft "Layanan tidak dihapus. Untuk menghapusnya nanti, jalankan perintah ini di Command Prompt sebagai administrator:$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- فارسی ----
!insertmacro LS FARSI ReinstTitle "از قبل نصب شده است"
!insertmacro LS FARSI ReinstSubtitle "روش ادامه را انتخاب کنید."
!insertmacro LS FARSI ReinstSame "${PRODUCT_NAME} $OldVer از قبل نصب شده است.$\r$\n$\r$\nمی‌خواهید چه کاری انجام دهید؟"
!insertmacro LS FARSI ReinstOlder "${PRODUCT_NAME} $OldVer نصب شده است. نسخهٔ ${VERSION} آن را به‌روز می‌کند.$\r$\n$\r$\nمی‌خواهید چگونه نصب کنید؟"
!insertmacro LS FARSI ReinstUnknown "یک نصب موجود از ${PRODUCT_NAME} پیدا شد.$\r$\n$\r$\nمی‌خواهید نسخهٔ ${VERSION} را چگونه نصب کنید؟"
!insertmacro LS FARSI ReinstNewer "نسخهٔ جدیدتری از ${PRODUCT_NAME} ($OldVer) نصب شده است. نصب نسخهٔ ${VERSION} یک بازگشت به نسخهٔ قدیمی‌تر است و تنظیمات ذخیره‌شده توسط نسخهٔ جدیدتر ممکن است در آن کار نکنند.$\r$\n$\r$\nمی‌خواهید چگونه ادامه دهید؟"
!insertmacro LS FARSI OptRepair "ترمیم / نصب مجدد ${PRODUCT_NAME} (تنظیمات حفظ می‌شود)"
!insertmacro LS FARSI OptUninstall "حذف ${PRODUCT_NAME}"
!insertmacro LS FARSI OptUpgrade "ارتقا به نسخهٔ ${VERSION} (پیشنهادی، تنظیمات حفظ می‌شود)"
!insertmacro LS FARSI OptDowngrade "بازگشت به نسخهٔ ${VERSION} (تنظیمات حفظ می‌شود)"
!insertmacro LS FARSI OptClean "ابتدا فایل‌های قدیمی برنامه حذف شوند، سپس نصب انجام شود (تنظیمات حفظ می‌شود)"
!insertmacro LS FARSI RunningMsg "${PRODUCT_NAME} در حال اجراست. برای ادامه باید همراه با هستهٔ آن بسته شود.$\r$\n$\r$\nبرای بستن آن همین حالا روی OK و برای خروج روی Cancel کلیک کنید."
!insertmacro LS FARSI CloseFailed "بستن ${PRODUCT_NAME} ممکن نشد. از نماد آن در سینی سیستم خارج شوید و سپس روی Retry کلیک کنید."
!insertmacro LS FARSI UninstallFailed "اجرای حذف‌کنندهٔ نصب موجود ممکن نشد."
!insertmacro LS FARSI DesktopShortcut "ایجاد میان‌بر روی دسکتاپ"
!insertmacro LS FARSI DeleteData "داده‌های برنامه نیز حذف شود (تنظیمات، پروفایل‌ها، گزارش‌ها و حافظهٔ نهان)"
!insertmacro LS FARSI ServiceAsk "سرویس ${PRODUCT_NAME} (مورد استفادهٔ حالت TUN) نصب شده است. حذف آن به مجوز مدیر نیاز دارد.$\r$\n$\r$\nهمین حالا حذف شود؟"
!insertmacro LS FARSI ServiceLeft "سرویس حذف نشد. برای حذف بعدی، این دستور را در Command Prompt با دسترسی مدیر اجرا کنید:$\r$\n$\r$\nsc delete ${SERVICE_NAME}"

; ---- العربية ----
!insertmacro LS ARABIC ReinstTitle "مثبَّت بالفعل"
!insertmacro LS ARABIC ReinstSubtitle "اختر طريقة المتابعة."
!insertmacro LS ARABIC ReinstSame "${PRODUCT_NAME} $OldVer مثبَّت بالفعل.$\r$\n$\r$\nماذا تريد أن تفعل؟"
!insertmacro LS ARABIC ReinstOlder "${PRODUCT_NAME} $OldVer مثبَّت. سيقوم الإصدار ${VERSION} بتحديثه.$\r$\n$\r$\nكيف تريد التثبيت؟"
!insertmacro LS ARABIC ReinstUnknown "تم العثور على تثبيت حالي لـ ${PRODUCT_NAME}.$\r$\n$\r$\nكيف تريد تثبيت الإصدار ${VERSION}؟"
!insertmacro LS ARABIC ReinstNewer "إصدار أحدث من ${PRODUCT_NAME} ($OldVer) مثبَّت. تثبيت الإصدار ${VERSION} يُعد تخفيضًا للإصدار، وقد لا تعمل الإعدادات التي حفظها الإصدار الأحدث معه.$\r$\n$\r$\nكيف تريد المتابعة؟"
!insertmacro LS ARABIC OptRepair "إصلاح / إعادة تثبيت ${PRODUCT_NAME} (مع الاحتفاظ بإعداداتك)"
!insertmacro LS ARABIC OptUninstall "إلغاء تثبيت ${PRODUCT_NAME}"
!insertmacro LS ARABIC OptUpgrade "الترقية إلى الإصدار ${VERSION} (موصى به، مع الاحتفاظ بإعداداتك)"
!insertmacro LS ARABIC OptDowngrade "التخفيض إلى الإصدار ${VERSION} (مع الاحتفاظ بإعداداتك)"
!insertmacro LS ARABIC OptClean "إزالة ملفات البرنامج القديمة أولًا ثم التثبيت (مع الاحتفاظ بإعداداتك)"
!insertmacro LS ARABIC RunningMsg "${PRODUCT_NAME} قيد التشغيل. يجب إغلاقه مع نواته للمتابعة.$\r$\n$\r$\nانقر على OK لإغلاقه الآن، أو على Cancel للخروج."
!insertmacro LS ARABIC CloseFailed "تعذّر إغلاق ${PRODUCT_NAME}. اخرج منه عبر أيقونة منطقة الإشعارات، ثم انقر على Retry."
!insertmacro LS ARABIC UninstallFailed "تعذّر تشغيل برنامج إلغاء التثبيت الخاص بالتثبيت الحالي."
!insertmacro LS ARABIC DesktopShortcut "إنشاء اختصار على سطح المكتب"
!insertmacro LS ARABIC DeleteData "حذف بيانات التطبيق أيضًا (الإعدادات والملفات الشخصية والسجلات والذاكرة المؤقتة)"
!insertmacro LS ARABIC ServiceAsk "خدمة ${PRODUCT_NAME} (المستخدمة في وضع TUN) مثبَّتة. تتطلب إزالتها إذن المسؤول.$\r$\n$\r$\nهل تريد إزالتها الآن؟"
!insertmacro LS ARABIC ServiceLeft "لم تتم إزالة الخدمة. لإزالتها لاحقًا، شغّل الأمر التالي في موجه الأوامر بصلاحيات المسؤول:$\r$\n$\r$\nsc delete ${SERVICE_NAME}"
