package app

import "github.com/egoist/mygo/plugins/updater"

// updaterStrings are the update window's texts in the languages of the
// interface that the plugin does not have.
var updaterStrings = map[string]updater.Strings{
	"id": {
		Title:              "Pembaruan Perangkat Lunak",
		MenuItem:           "Periksa Pembaruan…",
		Checking:           "Memeriksa pembaruan…",
		Cancel:             "Batal",
		OK:                 "OK",
		UpToDate:           "Anda sudah memakai versi terbaru!",
		UpToDateMessage:    "%[1]s %[2]s adalah versi terbaru yang tersedia saat ini.",
		Unavailable:        "Pembaruan Tidak Tersedia",
		UnavailableMessage: "%[1]s tidak dapat memperbarui dirinya di lokasi pemasangannya. Jika dipasang dengan pengelola paket, perbarui melalui pengelola paket tersebut.",
		DevelopmentBuild:   "Build pengembangan tidak memperbarui dirinya sendiri.",
		Error:              "Kesalahan Pembaruan!",
		CheckError:         "Terjadi kesalahan saat memeriksa pembaruan. Coba lagi nanti.",
		InstallError:       "Terjadi kesalahan saat memasang pembaruan. Coba lagi nanti.",
		Available:          "Versi baru %[1]s tersedia!",
		AvailableMessage:   "%[1]s %[2]s kini tersedia—Anda memakai %[3]s. Pasang sekarang?",
		ReleaseNotes:       "Catatan Rilis:",
		AutomaticDownloads: "Unduh dan pasang pembaruan secara otomatis di masa mendatang",
		Skip:               "Lewati Versi Ini",
		RemindLater:        "Ingatkan Nanti",
		Install:            "Pasang Pembaruan",
		Downloading:        "Mengunduh pembaruan…",
		Progress:           "%[1]s dari %[2]s",
		Megabytes:          "%s MB",
		Installing:         "Memasang pembaruan…",
		Ready:              "Siap Dimulai Ulang",
		ReadyMessage:       "%[1]s %[2]s sudah terpasang dan akan berjalan saat Anda membuka %[1]s berikutnya. Mulai ulang sekarang untuk memakainya.",
		Later:              "Nanti",
		Relaunch:           "Mulai Ulang Sekarang",
	},
	"vi": {
		Title:              "Cập nhật phần mềm",
		MenuItem:           "Kiểm tra cập nhật…",
		Checking:           "Đang kiểm tra cập nhật…",
		Cancel:             "Hủy",
		OK:                 "OK",
		UpToDate:           "Bạn đang dùng phiên bản mới nhất!",
		UpToDateMessage:    "%[1]s %[2]s hiện là phiên bản mới nhất.",
		Unavailable:        "Không thể cập nhật",
		UnavailableMessage: "%[1]s không thể tự cập nhật ở nơi được cài đặt. Nếu bạn cài bằng trình quản lý gói, hãy cập nhật bằng trình đó.",
		DevelopmentBuild:   "Bản dựng phát triển không tự cập nhật.",
		Error:              "Lỗi cập nhật!",
		CheckError:         "Đã xảy ra lỗi khi kiểm tra cập nhật. Vui lòng thử lại sau.",
		InstallError:       "Đã xảy ra lỗi khi cài đặt bản cập nhật. Vui lòng thử lại sau.",
		Available:          "Đã có phiên bản mới của %[1]s!",
		AvailableMessage:   "%[1]s %[2]s đã có—bạn đang dùng %[3]s. Bạn có muốn cài đặt ngay không?",
		ReleaseNotes:       "Ghi chú phát hành:",
		AutomaticDownloads: "Tự động tải về và cài đặt các bản cập nhật sau này",
		Skip:               "Bỏ qua phiên bản này",
		RemindLater:        "Nhắc tôi sau",
		Install:            "Cài đặt bản cập nhật",
		Downloading:        "Đang tải bản cập nhật…",
		Progress:           "%[1]s / %[2]s",
		Megabytes:          "%s MB",
		Installing:         "Đang cài đặt bản cập nhật…",
		Ready:              "Sẵn sàng khởi động lại",
		ReadyMessage:       "%[1]s %[2]s đã được cài đặt và sẽ chạy vào lần tới bạn mở %[1]s. Khởi động lại ngay để bắt đầu dùng.",
		Later:              "Để sau",
		Relaunch:           "Khởi động lại ngay",
	},
	"fa": {
		Title:              "به‌روزرسانی نرم‌افزار",
		MenuItem:           "بررسی به‌روزرسانی…",
		Checking:           "در حال بررسی به‌روزرسانی…",
		Cancel:             "لغو",
		OK:                 "تأیید",
		UpToDate:           "نسخهٔ شما به‌روز است!",
		UpToDateMessage:    "%[1]s %[2]s در حال حاضر تازه‌ترین نسخه است.",
		Unavailable:        "به‌روزرسانی در دسترس نیست",
		UnavailableMessage: "%[1]s نمی‌تواند خود را در محل نصبش به‌روز کند. اگر با یک مدیر بسته نصب شده است، آن را از همان‌جا به‌روز کنید.",
		DevelopmentBuild:   "نسخه‌های توسعه خودشان را به‌روز نمی‌کنند.",
		Error:              "خطای به‌روزرسانی!",
		CheckError:         "هنگام بررسی به‌روزرسانی خطایی رخ داد. لطفاً بعداً دوباره امتحان کنید.",
		InstallError:       "هنگام نصب به‌روزرسانی خطایی رخ داد. لطفاً بعداً دوباره امتحان کنید.",
		Available:          "نسخهٔ تازه‌ای از %[1]s در دسترس است!",
		AvailableMessage:   "%[1]s %[2]s اکنون در دسترس است؛ نسخهٔ شما %[3]s است. می‌خواهید همین حالا نصبش کنید؟",
		ReleaseNotes:       "یادداشت‌های انتشار:",
		AutomaticDownloads: "به‌روزرسانی‌ها از این پس خودکار دریافت و نصب شوند",
		Skip:               "رد کردن این نسخه",
		RemindLater:        "بعداً یادآوری کن",
		Install:            "نصب به‌روزرسانی",
		Downloading:        "در حال دریافت به‌روزرسانی…",
		Progress:           "%[1]s از %[2]s",
		Megabytes:          "%s مگابایت",
		Installing:         "در حال نصب به‌روزرسانی…",
		Ready:              "آمادهٔ اجرای دوباره",
		ReadyMessage:       "%[1]s %[2]s نصب شد و دفعهٔ بعد که %[1]s را باز کنید اجرا می‌شود. برای استفاده از آن، همین حالا دوباره اجرا کنید.",
		Later:              "بعداً",
		Relaunch:           "اجرای دوباره",
	},
	"ar": {
		Title:              "تحديث البرنامج",
		MenuItem:           "التحقق من وجود تحديثات…",
		Checking:           "جارٍ التحقق من وجود تحديثات…",
		Cancel:             "إلغاء",
		OK:                 "حسنًا",
		UpToDate:           "أنت تستخدم أحدث إصدار!",
		UpToDateMessage:    "%[1]s %[2]s هو أحدث إصدار متاح حاليًا.",
		Unavailable:        "التحديثات غير متاحة",
		UnavailableMessage: "لا يمكن لـ %[1]s تحديث نفسه في مكان تثبيته. إن ثبّته مدير حزم، فحدّثه من خلاله.",
		DevelopmentBuild:   "إصدارات التطوير لا تحدّث نفسها.",
		Error:              "خطأ في التحديث!",
		CheckError:         "حدث خطأ أثناء التحقق من وجود تحديثات. يُرجى المحاولة لاحقًا.",
		InstallError:       "حدث خطأ أثناء تثبيت التحديث. يُرجى المحاولة لاحقًا.",
		Available:          "يتوفر إصدار جديد من %[1]s!",
		AvailableMessage:   "يتوفر الآن %[1]s %[2]s، ولديك %[3]s. هل تريد تثبيته الآن؟",
		ReleaseNotes:       "ملاحظات الإصدار:",
		AutomaticDownloads: "تنزيل التحديثات وتثبيتها تلقائيًا في المستقبل",
		Skip:               "تخطي هذا الإصدار",
		RemindLater:        "ذكّرني لاحقًا",
		Install:            "تثبيت التحديث",
		Downloading:        "جارٍ تنزيل التحديث…",
		Progress:           "%[1]s من %[2]s",
		Megabytes:          "%s ميغابايت",
		Installing:         "جارٍ تثبيت التحديث…",
		Ready:              "جاهز لإعادة التشغيل",
		ReadyMessage:       "تم تثبيت %[1]s %[2]s وسيعمل في المرة القادمة التي تفتح فيها %[1]s. أعد التشغيل الآن لبدء استخدامه.",
		Later:              "لاحقًا",
		Relaunch:           "إعادة التشغيل الآن",
	},
}
