import { useEffect, useState } from "react";
import { App } from "../mygo";

/** QRCode shows text as a QR code, drawn by the Go side. */
export function QRCode({ text, size = 180 }: { text: string; size?: number }) {
  const [svg, setSvg] = useState("");
  useEffect(() => {
    let live = true;
    App.qr(text)
      .then((s) => live && setSvg(s))
      .catch(() => live && setSvg(""));
    return () => {
      live = false;
    };
  }, [text]);
  if (!svg) return <div className="skeleton" style={{ width: size, height: size }} />;
  return (
    <div
      style={{ width: size, height: size, borderRadius: 10, overflow: "hidden", border: "1px solid var(--border)", background: "#fff" }}
      // The SVG is generated by the app from the text: paths only.
      dangerouslySetInnerHTML={{ __html: svg.replace("<svg ", `<svg width="${size}" height="${size}" `) }}
    />
  );
}
