// Code generated by `mygo generate`. DO NOT EDIT.

import { call, event, type Channel } from "mygo-runtime";

// ---- Types ----

/** AppInfo describes the app. */
export interface AppInfo {
  name: string;
  version: string;
  coreVersion: string;
  os: string;
  arch: string;
  dataDir: string;
  coreDir: string;
  logsDir: string;
  hostname: string;
  locale: string;
  isDev: boolean;
  keyring: string;
  keyringSecure: boolean;
  startedAt: string;
}

/** AppState is the state of the app the interface shows everywhere. */
export interface AppState {
  ready: boolean;
  core: State;
  /** Service is the privileged service, which TUN needs. */
  service: ServiceState;
  /** SystemProxy is on when the app set the system's proxy. */
  systemProxy: boolean;
  systemProxyError?: string;
  /** Tun is on when the core runs TUN. */
  tun: boolean;
  /**
   * TunAvailable reports that TUN can be turned on: the core has the
   * privileges, or the service can give them.
   */
  tunAvailable: boolean;
  mode: string;
  profileUid: string;
  profileName: string;
  mixedPort: number;
  lightweight: boolean;
  /** ConfigError is why the last configuration did not apply. */
  configError?: string;
  appliedAt?: string;
}

/** Backup makes local backups. */
export interface Backup {
  /** 0: off */
  autoIntervalHours: number;
  onChange: boolean;
  keep: number;
}

/** BackupInfo describes a snapshot on the server or the device. */
export interface BackupInfo {
  name: string;
  size: number;
  created: string;
  device: string;
  remote: boolean;
}

/** Clash is the part of the core's configuration the app owns. */
export interface Clash {
  /** rule, global, direct */
  mode: string;
  mixedPort: number;
  socksPort: number;
  socksEnabled: boolean;
  httpPort: number;
  httpEnabled: boolean;
  redirPort: number;
  redirEnabled: boolean;
  tproxyPort: number;
  tproxyEnabled: boolean;
  allowLan: boolean;
  lanAuth: LANAuth;
  ipv6: boolean;
  /** debug, info, warning, error, silent */
  logLevel: string;
  unifiedDelay: boolean;
  tcpConcurrent: boolean;
  /** "", always, strict, off */
  findProcessMode: string;
  interface: string;
  controller: Controller;
}

/** Conflict is a path both sides changed, which waits for the user. */
export interface Conflict {
  path: string;
  localModified: string;
  remoteModified: string;
  remoteDevice: string;
  localDeleted: boolean;
  remoteDeleted: boolean;
  detected: string;
}

/** Connection is an open connection. */
export interface Connection {
  id: string;
  metadata: ConnectionMetadata;
  upload: number;
  download: number;
  start: string;
  chains: string[];
  rule: string;
  rulePayload: string;
  /**
   * UploadSpeed and DownloadSpeed are computed by the app between two
   * snapshots, in bytes per second.
   */
  uploadSpeed?: number;
  downloadSpeed?: number;
}

/** ConnectionMetadata describes the endpoints of a connection. */
export interface ConnectionMetadata {
  network: string;
  type: string;
  sourceIP: string;
  destinationIP: string;
  sourcePort: string;
  destinationPort: string;
  inboundIP?: string;
  inboundPort?: string;
  inboundName?: string;
  inboundUser?: string;
  host: string;
  sniffHost?: string;
  dnsMode?: string;
  uid?: number;
  process?: string;
  processPath?: string;
  specialProxy?: string;
  specialRules?: string;
  remoteDestination?: string;
  dscp?: number;
  destinationGeoIP?: string[];
  destinationIPASN?: string;
}

/** Connections is GET /connections. */
export interface Connections {
  downloadTotal: number;
  uploadTotal: number;
  connections: Connection[];
  memory: number;
}

/** Controller is the core's REST API on a TCP port, for dashboards. */
export interface Controller {
  enabled: boolean;
  address: string;
  secret: string;
  allowOrigins: string[];
  allowPrivateNetwork: boolean;
}

/** DNS overrides the DNS of profiles. */
export interface DNS {
  /**
   * DefaultOverride applies the override to profiles the user has not
   * decided for.
   */
  defaultOverride: boolean;
  /** Profiles records the decision for each profile, by uid. */
  profiles: Record<string, boolean>;
  /** Config is the override, YAML with dns and hosts. */
  config: string;
}

/** DNSAnswer is a record of a DNS query. */
export interface DNSAnswer {
  name: string;
  type: number;
  TTL: number;
  data: string;
}

/** DNSQueryResult is GET /dns/query. */
export interface DNSQueryResult {
  Status: number;
  Question: unknown[];
  Answer?: DNSAnswer[];
}

/** DeviceInfo is a device that syncs. */
export interface DeviceInfo {
  id: string;
  name: string;
  os: string;
  lastSync: string;
  this: boolean;
}

/** HomeCard is a card of the home page. */
export interface HomeCard {
  id: string;
  visible: boolean;
}

/** Hotkeys are global keyboard shortcuts, by action. */
export interface Hotkeys {
  enabled: boolean;
  bindings: Record<string, string>;
}

/** IPInfo is what the world sees of the connection. */
export interface IPInfo {
  ip: string;
  country: string;
  countryCode: string;
  region: string;
  city: string;
  isp: string;
  asn: string;
  timezone: string;
  latitude: number;
  longitude: number;
  /** the Cloudflare data center */
  colo?: string;
  source: string;
}

/**
 * LANAuth is the login the proxy ports ask of other devices when allow-lan
 * is on. This device is let in without it.
 */
export interface LANAuth {
  enabled: boolean;
  username: string;
  password: string;
}

/** Latency is how delays are tested. */
export interface Latency {
  url: string;
  timeoutMs: number;
  autoCheck: boolean;
  autoCheckMinutes: number;
}

/**
 * Lightweight mode closes the window to save memory, keeping the core,
 * the tray and the quick panel.
 */
export interface Lightweight {
  autoEnter: boolean;
  delayMinutes: number;
}

/** LogEntry is a line a script printed, or a note about an extension. */
export interface LogEntry {
  /** log, info, warn, error, debug, table, exception */
  level: string;
  message: string;
}

/** LogEvent is a line of /logs. */
export interface LogEvent {
  /** debug, info, warning, error */
  type: string;
  payload: string;
  /** set by the app when it receives the line */
  time: string;
}

/** Logs is the app's own logging. */
export interface Logs {
  /** debug, info, warn, error */
  level: string;
  maxSizeMb: number;
  maxFiles: number;
  /** 0: never */
  autoCleanDays: number;
}

/** Memory is a sample of /memory, in bytes. */
export interface Memory {
  inuse: number;
  oslimit: number;
}

/** NameLists are the names of a profile's proxies and groups. */
export interface NameLists {
  proxies: string[];
  groups: string[];
  /** Builtin are the policies every configuration has: DIRECT, REJECT... */
  builtin: string[];
}

/** NetIface is a network interface. */
export interface NetIface {
  name: string;
  mac: string;
  addrs: string[];
  up: boolean;
}

/** NewProfile describes a profile to create. */
export interface NewProfile {
  /** remote or local */
  type: string;
  name: string;
  desc: string;
  url: string;
  /** a local profile's YAML; "" for the template */
  content: string;
  option: Option;
}

/** Notice is a message for the user, shown as a toast. */
export interface Notice {
  /** info, success, warning, error */
  level: string;
  message: string;
  detail?: string;
  /**
   * Action is what a button of the toast does: install-service,
   * open-settings, open-sync, ...
   */
  action?: string;
  /**
   * Page is where clicking the system notification leads: a page such
   * as "profiles", or a tab of the settings as "settings/sync". Empty
   * means home.
   */
  page?: string;
}

/** Option configures how a profile updates and which extensions it uses. */
export interface Option {
  userAgent?: string;
  /** WithProxy downloads through the core's proxy. */
  withProxy?: boolean;
  /**
   * UpdateInterval updates the subscription every so many minutes; 0
   * uses the provider's suggestion, -1 never.
   */
  updateInterval?: number;
  /** TimeoutSeconds bounds a download; 0 is 60 seconds. */
  timeoutSeconds?: number;
  /** Insecure accepts invalid TLS certificates. Dangerous. */
  insecure?: boolean;
  /** NoAutoUpdate stops scheduled updates. */
  noAutoUpdate?: boolean;
  /** UIDs of the profile's extensions. */
  merge?: string;
  script?: string;
  rules?: string;
  proxies?: string;
  groups?: string;
}

/** Patch describes changes to an item. */
export interface Patch {
  name?: string;
  desc?: string;
  url?: string;
  option?: Option;
}

/** Profile is a profile or an extension. */
export interface Profile {
  uid: string;
  type: string;
  name: string;
  desc?: string;
  /** URL is the subscription of a remote profile. */
  url?: string;
  /** Home is the provider's web page, from its profile-web-page-url header. */
  home?: string;
  /** Updated is when the content last changed, in Unix seconds. */
  updated: number;
  usage?: Usage;
  option: Option;
  /** Selected remembers the selection of each selector group. */
  selected?: Selected[];
  /** LastError is why the last update failed, "" when it worked. */
  lastError?: string;
  /** Size is the size of the content in bytes. */
  size: number;
  /** Proxies and Groups count what the profile defines. */
  proxies: number;
  groups: number;
  /**
   * Converted reports a subscription of share links that the app turned
   * into a configuration.
   */
  converted?: boolean;
  /**
   * Suggested is the update interval the provider suggested at the last
   * download, in minutes; 0 when it suggested none.
   */
  suggestedInterval?: number;
}

/** ProfilesView is the list of profiles the page shows. */
export interface ProfilesView {
  current: string;
  items: Profile[];
  /** NextUpdates is when remote profiles update next, by UID. */
  nextUpdates: Record<string, string>;
  /** DNS reports, by UID, whether the DNS override applies. */
  dns: Record<string, boolean>;
}

/** ProviderView is a provider of proxies. */
export interface ProviderView {
  name: string;
  vehicleType: string;
  count: number;
  updatedAt?: string;
  subscriptionInfo?: SubscriptionInfo;
  testUrl?: string;
}

/** ProxiesView is what the proxies page shows. */
export interface ProxiesView {
  mode: string;
  groups: ProxyGroup[];
  /** Global is the group of global mode. */
  global?: ProxyGroup;
  /** Direct lists the proxies of the configuration, for direct mode. */
  proxies: ProxyItem[];
  providers: ProviderView[];
}

/** Proxy is a system proxy setting. */
export interface Proxy {
  enabled: boolean;
  host: string;
  port: number;
  /** Bypass lists hosts and networks that skip the proxy. */
  bypass: string[];
  /**
   * PAC is the URL of a proxy auto-configuration script, used instead of
   * Host and Port when set.
   */
  pac?: string;
}

/** ProxyGroup is a group of proxies. */
export interface ProxyGroup {
  name: string;
  type: string;
  now: string;
  fixed?: string;
  hidden: boolean;
  icon?: string;
  testUrl?: string;
  all: ProxyItem[];
}

/** ProxyItem is a member of a group. */
export interface ProxyItem {
  name: string;
  type: string;
  udp: boolean;
  xudp?: boolean;
  tfo?: boolean;
  mptcp?: boolean;
  alive: boolean;
  /** ms; 0 failed; -1 untested */
  delay: number;
  provider?: string;
  isGroup: boolean;
  now?: string;
  icon?: string;
  hidden?: boolean;
}

/** Report says what a sync did. */
export interface Report {
  pushed: string[];
  pulled: string[];
  merged: string[];
  copies: string[];
  conflicts: Conflict[];
  retries: number;
  devices: number;
  Duration: number;
}

/** Rule is a rule of the running configuration. */
export interface Rule {
  index: number;
  type: string;
  payload: string;
  proxy: string;
  size: number;
  extra?: RuleExtra;
}

/** RuleExtra is the statistics of a rule. */
export interface RuleExtra {
  disabled: boolean;
  hitCount: number;
  hitAt: string;
  missCount: number;
  missAt: string;
}

/** RuleProvider is a provider of rules. */
export interface RuleProvider {
  name: string;
  type: string;
  vehicleType: string;
  behavior: string;
  format: string;
  ruleCount: number;
  updatedAt?: string;
}

/** RulesView is the rules and their providers. */
export interface RulesView {
  rules: Rule[];
  providers: RuleProvider[];
}

/** RuntimeInfo describes the configuration last applied. */
export interface RuntimeInfo {
  profileUid: string;
  appliedAt: string;
  /** Notes counts the notes extensions left, by extension. */
  notes: Record<string, number>;
}

/** Selected is the selection of a group. */
export interface Selected {
  name: string;
  now: string;
}

/** Selection is a group's selection. */
export interface Selection {
  group: string;
  now: string;
}

/** SeqPatch is a rules, proxies or groups extension. */
export interface SeqPatch {
  prepend: unknown[];
  append: unknown[];
  delete: string[];
}

/** ServiceState describes the privileged service. */
export interface ServiceState {
  supported: boolean;
  installed: boolean;
  version?: string;
  /**
   * Outdated reports a service of another version than the app's, as
   * after the app updated: it runs no core until it is updated too.
   */
  outdated: boolean;
  error?: string;
}

/** Settings is everything the user sets in the app. */
export interface Settings {
  /**
   * Language is the language of the interface: zh-CN, en, or "" to
   * follow the system.
   */
  language: string;
  /** Theme is system, light or dark. */
  theme: string;
  /** OLED makes the dark theme pure black. */
  oled: boolean;
  /** Accent is the accent color, #RRGGBB, or "" for the app's. */
  accent: string;
  fontFamily: string;
  /** CustomCSS is added to the pages of the app. */
  customCss: string;
  /** StartPage is the page the window opens on. */
  startPage: string;
  /** SilentStart starts the app in the tray, without its window. */
  silentStart: boolean;
  /** TrayClick is what clicking the tray icon does: menu, window or panel. */
  trayClick: string;
  /**
   * CopyEnvType is the shell of "Copy environment": posix, cmd,
   * powershell, fish or nushell.
   */
  copyEnvType: string;
  notifications: boolean;
  /**
   * AutoCloseConnections closes connections when the selected proxy or
   * the mode changes, so that they reconnect through the new route.
   */
  autoCloseConnections: boolean;
  /** BuiltinEnhanced makes old profiles work with mihomo. */
  builtinEnhanced: boolean;
  /**
   * CoreMode chooses how the core runs: auto (the service when installed,
   * else a child process), sidecar or service.
   */
  coreMode: string;
  /** WebUIs are dashboards to open, with %host, %port and %secret. */
  webUis: string[];
  ui: UI;
  systemProxy: SystemProxy;
  tun: Tun;
  /**
   * WebRTCGuard keeps WebRTC in browsers from showing the address behind
   * the proxy, through their policies (Windows).
   */
  webrtcGuard: boolean;
  clash: Clash;
  dns: DNS;
  latency: Latency;
  hotkeys: Hotkeys;
  tray: Tray;
  lightweight: Lightweight;
  logs: Logs;
  tailscale: Tailscale;
  sync: Sync;
  backup: Backup;
  updates: Updates;
}

/** Site is a site whose delay is tested. */
export interface Site {
  id: string;
  name: string;
  url: string;
  /** global or domestic */
  group?: string;
}

/** SiteResult is the delay of a site, 0 when it failed. */
export interface SiteResult {
  id: string;
  delayMs: number;
  status: number;
  error?: string;
}

/** State describes the core. */
export interface State {
  status: string;
  /** sidecar or service */
  mode: string;
  error?: string;
  pid?: number;
  /** the core binary's app version */
  version?: string;
  /** mihomo's */
  coreVersion?: string;
  privileged: boolean;
  startedAt?: string;
  restarts: number;
}

/**
 * StatsItem is the traffic of an app, site or node. Other collects the
 * rest, and has no name.
 */
export interface StatsItem {
  name: string;
  other?: boolean;
  up: number;
  down: number;
}

/** StatsPoint is the traffic of a day, or of an hour of a day. */
export interface StatsPoint {
  /** the date, or the hour */
  label: string;
  up: number;
  down: number;
}

/**
 * StatsQuery asks for a range of days. Range is "today", "7d" or "30d";
 * anything else uses From and To ("2006-01-02", both included). Top is
 * how many apps, sites and nodes to list.
 */
export interface StatsQuery {
  range: string;
  from?: string;
  to?: string;
  top: number;
}

/** StatsReport is the answer to a query. */
export interface StatsReport {
  from: string;
  to: string;
  up: number;
  down: number;
  days: StatsPoint[];
  /** when the range is a single day */
  hours: StatsPoint[];
  apps: StatsItem[];
  sites: StatsItem[];
  nodes: StatsItem[];
}

/** StoreApp is an app container: a Store app. */
export interface StoreApp {
  /** SID identifies it; exemptions are by SID. */
  sid: string;
  /**
   * Name is its package family name, such as
   * Microsoft.WindowsStore_8wekyb3d8bbwe.
   */
  name: string;
  displayName: string;
  exempt: boolean;
}

/** SubscriptionInfo is the traffic and expiry a provider reports. */
export interface SubscriptionInfo {
  Upload: number;
  Download: number;
  Total: number;
  Expire: number;
}

/**
 * Sync synchronizes settings and profiles between devices through WebDAV,
 * encrypted on the device.
 */
export interface Sync {
  enabled: boolean;
  url: string;
  username: string;
  /** Dir is the folder of the app on the server. */
  dir: string;
  /**
   * IntervalMinutes syncs periodically; 0 syncs only on demand and on
   * change.
   */
  intervalMinutes: number;
  onChange: boolean;
  /**
   * ConflictPolicy resolves a file both sides changed: ask, newest,
   * local or remote.
   */
  conflictPolicy: string;
  /** Categories are what syncs: profiles, settings, dns, tailscale. */
  categories: string[];
  /** AllowInsecure allows http:// for servers on the local network. */
  allowInsecure: boolean;
  /**
   * PinnedKey is the SHA-256 of the server certificate's public key,
   * base64, to trust a self-signed certificate.
   */
  pinnedKey: string;
}

/** SyncProbe is what a test of the server found. */
export interface SyncProbe {
  reachable: boolean;
  hasVault: boolean;
  /** Plain is set when the vault found is not encrypted. */
  plain: boolean;
  error?: string;
  /**
   * Fingerprint and Trusted describe the server's key, for pinning one
   * that certificate authorities do not trust.
   */
  fingerprint?: string;
  trusted: boolean;
}

/** SyncSetup sets sync up. */
export interface SyncSetup {
  url: string;
  username: string;
  /** "" keeps the saved one */
  password: string;
  dir: string;
  passphrase: string;
  /**
   * Plain creates a vault that is not encrypted; an existing vault
   * stays as it is.
   */
  plain: boolean;
  allowInsecure: boolean;
  pinnedKey: string;
}

/** SyncStatus is the state of sync. */
export interface SyncStatus {
  configured: boolean;
  enabled: boolean;
  running: boolean;
  pending: boolean;
  lastSync?: string;
  lastError?: string;
  conflicts: Conflict[];
  devices: number;
  deviceId: string;
  deviceName: string;
  keyId?: string;
  /** Plain is set when the vault on the server is not encrypted. */
  plain: boolean;
  report?: Report;
  nextSync?: string;
  labels: Record<string, string>;
}

/** SystemProxy is the proxy the app sets for the operating system. */
export interface SystemProxy {
  enabled: boolean;
  /** Host is the address applications reach the proxy at. */
  host: string;
  /**
   * Bypass lists hosts that skip the proxy, separated by commas,
   * semicolons or new lines.
   */
  bypass: string;
  useDefaultBypass: boolean;
  /** PAC sets a proxy auto-configuration script instead of a proxy. */
  pac: boolean;
  pacScript: string;
  /** Guard sets the proxy again when another app changes it. */
  guard: boolean;
  /** seconds */
  guardInterval: number;
}

/** Tailscale connects the app to a tailnet. */
export interface Tailscale {
  /**
   * Mode is off; embedded, a node the core runs, which needs no
   * Tailscale app; or system, the Tailscale app installed on the
   * computer.
   */
  mode: string;
  /** Embedded node. */
  hostname: string;
  controlUrl: string;
  ephemeral: boolean;
  acceptRoutes: boolean;
  exitNode: string;
  exitNodeAllowLan: boolean;
  /**
   * ControlVia is the proxy the node reaches its coordination server
   * and relays through, "" for direct.
   */
  controlVia: string;
  /** ProxyName names the node's outbound in configurations. */
  proxyName: string;
  /** JoinSelector adds the outbound to the first selector group. */
  joinSelector: boolean;
  /** RouteSubnets sends the subnets peers advertise through the tailnet. */
  routeSubnets: boolean;
  /**
   * ShareProxy offers the mixed proxy to the user's other devices on the
   * tailnet, at ShareProxyPort of the node.
   */
  shareProxy: boolean;
  shareProxyPort: number;
  /**
   * Both modes.
   * MagicDNS resolves tailnet names through Tailscale.
   */
  magicDns: boolean;
  /**
   * Coexist keeps the core's TUN and DNS away from the installed
   * Tailscale (system mode).
   */
  coexist: boolean;
}

/** TailscalePeer is a node of the tailnet. */
export interface TailscalePeer {
  id: string;
  hostName: string;
  dnsName: string;
  os: string;
  user?: string;
  tailscaleIps: string[];
  online: boolean;
  active: boolean;
  lastSeen?: string;
  /** the exit node in use */
  exitNode: boolean;
  /** can be one */
  exitNodeOption: boolean;
  relay?: string;
  curAddr?: string;
  rxBytes: number;
  txBytes: number;
  primaryRoutes?: string[];
  tags?: string[];
  keyExpiry?: string;
  expired: boolean;
}

/** TailscalePingResult is the result of a ping. */
export interface TailscalePingResult {
  latencyMs: number;
  /** the direct address, if any */
  endpoint?: string;
  /** the relay region, if relayed */
  derp?: string;
  err?: string;
}

/** TailscalePrefs changes preferences of a running node. */
export interface TailscalePrefs {
  acceptRoutes?: boolean;
  exitNode?: string;
  exitNodeAllowLan?: boolean;
  shieldsUp?: boolean;
}

/**
 * TailscaleStatus is the state of a tailnet node: the embedded node of the
 * core, or the Tailscale client installed on the computer.
 */
export interface TailscaleStatus {
  /** Source is "embedded" or "system". */
  source: string;
  /** Available reports whether there is a node to talk to. */
  available: boolean;
  /**
   * BackendState is Tailscale's: NoState, NeedsLogin, NeedsMachineAuth,
   * Stopped, Starting or Running.
   */
  backendState: string;
  authUrl?: string;
  self?: TailscalePeer;
  peers: TailscalePeer[];
  user?: TailscaleUser;
  tailnetName?: string;
  magicDnsSuffix?: string;
  magicDns: boolean;
  exitNodeId?: string;
  acceptRoutes: boolean;
  shieldsUp: boolean;
  /** subnets peers advertise, primary routes */
  routes?: string[];
  health?: string[];
  version?: string;
  /** system client's interface */
  interface?: string;
  shareProxy?: string;
  error?: string;
  updatedAt: string;
  /**
   * StateVersion counts the writes of the embedded node's state; the app
   * fetches the state again when it moves.
   */
  stateVersion?: number;
  extra?: unknown;
}

/** TailscaleUser is the account a node belongs to. */
export interface TailscaleUser {
  loginName: string;
  displayName: string;
  profilePicUrl?: string;
}

/** Traffic is a sample of /traffic, in bytes per second and in total. */
export interface Traffic {
  up: number;
  down: number;
  upTotal: number;
  downTotal: number;
}

/** Tray is what the tray icon shows. */
export interface Tray {
  /** ShowSpeed shows the traffic next to the icon (macOS). */
  showSpeed: boolean;
  /** Groups shows proxy groups as submenus, inline, or off. */
  groups: string;
  inlineModes: boolean;
}

/** Tun is the virtual network interface, which captures all traffic. */
export interface Tun {
  enabled: boolean;
  /** system, gvisor, mixed */
  stack: string;
  device: string;
  autoRoute: boolean;
  strictRoute: boolean;
  autoDetectInterface: boolean;
  /** Linux */
  autoRedirect: boolean;
  dnsHijack: string[];
  mtu: number;
  routeExcludeAddress: string[];
}

/** UI is how the interface looks. */
export interface UI {
  collapseNav: boolean;
  trafficGraph: boolean;
  memoryUsage: boolean;
  groupIcons: boolean;
  /** top-right, top-left, bottom-right, bottom-left */
  toastPosition: string;
  /** 0: as many as fit */
  proxyColumns: number;
  /** card, list */
  proxyLayout: string;
  pauseOnBlur: boolean;
  homeCards: HomeCard[];
  /**
   * Nav lists the pages of the sidebar in order; pages missing from it
   * are hidden.
   */
  nav: string[];
  /**
   * NavKnown lists the pages the sidebar has offered, so a page added
   * in an update shows up once, while one the user hid stays hidden.
   */
  navKnown?: string[];
}

/** Unlock is the availability of a service. */
export interface Unlock {
  id: string;
  name: string;
  /** yes, no, partial, failed, pending */
  status: string;
  region?: string;
  detail?: string;
  at?: string;
}

/** UpdateState tells the page about updates of the app. */
export interface UpdateState {
  /**
   * Supported is whether this install updates itself. When it does not,
   * Reason says why: "dev" for development builds, "package" for apps
   * that a package manager or an AppImage holds.
   */
  supported: boolean;
  reason?: string;
  /**
   * AutomaticDownloads installs updates found in the background without
   * asking.
   */
  automaticDownloads: boolean;
  /**
   * LastCheck is when the app last checked successfully, in Unix
   * milliseconds; 0 for never.
   */
  lastCheck: number;
  /** Checking is set during a background check. */
  checking: boolean;
  /**
   * Ready is the version installed in the background, which runs when
   * the app restarts.
   */
  ready?: string;
}

/**
 * Updates is how the app looks for new versions of itself. Whether it
 * installs them without asking is the updater's, which its window changes
 * too.
 */
export interface Updates {
  /**
   * AutoCheck looks for a new version in the background, every
   * Interval: hourly, daily, weekly or monthly.
   */
  autoCheck: boolean;
  interval: string;
}

/** Usage is the traffic and expiry a subscription reports. */
export interface Usage {
  upload: number;
  download: number;
  total: number;
  /** Unix seconds, 0 for never */
  expire: number;
}

// ---- Services ----

/** AppService is the app as a whole. */
export const App = {
  /** AutoLaunch reports whether the app starts at login. */
  autoLaunch(): Promise<boolean> {
    return call("App.AutoLaunch");
  },
  /** CopyEnv copies the environment command. */
  copyEnv(): Promise<string> {
    return call("App.CopyEnv");
  },
  /** CopyText puts text on the clipboard. */
  copyText(text: string): Promise<void> {
    return call("App.CopyText", text);
  },
  /**
   * Diagnostics returns a report for bug reports, without secrets, and copies
   * it.
   */
  diagnostics(): Promise<string> {
    return call("App.Diagnostics");
  },
  /** EnterLightweight closes the window, keeping the core and the tray. */
  enterLightweight(): Promise<void> {
    return call("App.EnterLightweight");
  },
  /**
   * EnvCommand returns the shell command that points programs at the proxy,
   * for the shell of the settings.
   */
  envCommand(): Promise<string> {
    return call("App.EnvCommand");
  },
  /** Info describes the app. */
  info(): Promise<AppInfo> {
    return call("App.Info");
  },
  /** NetworkInterfaces lists the computer's network interfaces. */
  networkInterfaces(): Promise<NetIface[]> {
    return call("App.NetworkInterfaces");
  },
  /** OpenDir opens a directory of the app: data, core or logs. */
  openDir(kind: string): Promise<void> {
    return call("App.OpenDir", kind);
  },
  /** OpenURL opens a URL in the browser. */
  openURL(u: string): Promise<void> {
    return call("App.OpenURL", u);
  },
  /** QR returns an SVG of a QR code of text. */
  qr(text: string): Promise<string> {
    return call("App.QR", text);
  },
  /** Quit quits the app. */
  quit(): Promise<void> {
    return call("App.Quit");
  },
  /** Relaunch restarts the app. */
  relaunch(): Promise<void> {
    return call("App.Relaunch");
  },
  /** SetAutoLaunch starts the app at login, or not. */
  setAutoLaunch(on: boolean): Promise<void> {
    return call("App.SetAutoLaunch", on);
  },
  /** State returns the app's state. */
  state(): Promise<AppState> {
    return call("App.State");
  },
  /**
   * TakePage returns, once, the page a window just created should show
   * (the target of a notification or a tray item), or "".
   */
  takePage(): Promise<string> {
    return call("App.TakePage");
  },
} as const;

/** SettingsService reads and changes the settings. */
export const Settings = {
  /** DefaultBypass returns the hosts that skip the system proxy by default. */
  defaultBypass(): Promise<string[]> {
    return call("Settings.DefaultBypass");
  },
  /** Defaults returns the settings of a new installation. */
  defaults(): Promise<Settings> {
    return call("Settings.Defaults");
  },
  /** Get returns the settings. */
  get(): Promise<Settings> {
    return call("Settings.Get");
  },
  /**
   * Patch changes the settings with a JSON merge patch and does what the
   * change implies; it returns the settings after.
   */
  patch(patch: Record<string, unknown>): Promise<Settings> {
    return call("Settings.Patch", patch);
  },
  /** RandomSecret returns a random secret for the controller. */
  randomSecret(): Promise<string> {
    return call("Settings.RandomSecret");
  },
  /** SystemProxy returns the system's proxy setting as it is now. */
  systemProxy(): Promise<Proxy> {
    return call("Settings.SystemProxy");
  },
} as const;

/** Profiles manages profiles and their extensions. */
export const Profiles = {
  /**
   * Activate makes a profile current and applies it. When the core rejects
   * it, the previous profile stays current.
   */
  activate(uid: string): Promise<void> {
    return call("Profiles.Activate", uid);
  },
  /** Content returns what an item holds: a profile's YAML, an extension's. */
  content(uid: string): Promise<string> {
    return call("Profiles.Content", uid);
  },
  /** Create creates a profile: a remote one downloads first. */
  create(np: NewProfile): Promise<Profile> {
    return call("Profiles.Create", np);
  },
  /** Delete deletes a profile and its extensions. */
  delete(uid: string): Promise<void> {
    return call("Profiles.Delete", uid);
  },
  /**
   * Export saves an item's content to a file the user picks. The file is
   * not encrypted.
   */
  export(uid: string): Promise<string> {
    return call("Profiles.Export", uid);
  },
  /**
   * Extension returns the UID of a profile's extension of a kind (rules,
   * proxies, groups, merge, script), creating it the first time.
   */
  extension(uid: string, kind: string): Promise<string> {
    return call("Profiles.Extension", uid, kind);
  },
  /** Get returns an item. */
  get(uid: string): Promise<Profile> {
    return call("Profiles.Get", uid);
  },
  /**
   * HasDNS reports whether a profile configures DNS itself, which the DNS
   * override would replace.
   */
  hasDNS(uid: string): Promise<boolean> {
    return call("Profiles.HasDNS", uid);
  },
  /** ImportFile asks for a file and creates a local profile from it. */
  importFile(): Promise<Profile | null> {
    return call("Profiles.ImportFile");
  },
  /** List returns the profiles. */
  list(): Promise<ProfilesView> {
    return call("Profiles.List");
  },
  /**
   * Logs returns what the extensions noted and printed at the last apply,
   * by UID.
   */
  logs(): Promise<Record<string, LogEntry[]>> {
    return call("Profiles.Logs");
  },
  /**
   * Names returns the names of a profile's proxies and groups, for the
   * extension editors.
   */
  names(uid: string): Promise<NameLists> {
    return call("Profiles.Names", uid);
  },
  /**
   * ParseLinks turns share links (vmess://, ss://, trojan://, vless://,
   * hysteria2://, ..., or a base64 list of them) into proxies.
   */
  parseLinks(text: string): Promise<Record<string, unknown>[]> {
    return call("Profiles.ParseLinks", text);
  },
  /** Patch changes a profile's name, description, URL or options. */
  patch(uid: string, p: Patch): Promise<Profile> {
    return call("Profiles.Patch", uid, p);
  },
  /** Reorder orders the profiles. */
  reorder(uids: string[]): Promise<void> {
    return call("Profiles.Reorder", uids);
  },
  /** RulesOf returns the rules a profile has itself, for the rules editor. */
  rulesOf(uid: string): Promise<string[]> {
    return call("Profiles.RulesOf", uid);
  },
  /** RuntimeYAML returns the configuration the core runs. */
  runtimeYAML(): Promise<string> {
    return call("Profiles.RuntimeYAML");
  },
  /**
   * SaveContent replaces what an item holds, after checking it: profiles
   * are checked by the core.
   */
  saveContent(uid: string, content: string): Promise<void> {
    return call("Profiles.SaveContent", uid, content);
  },
  /** SaveSeq writes a rules, proxies or groups extension. */
  saveSeq(uid: string, p: SeqPatch): Promise<void> {
    return call("Profiles.SaveSeq", uid, p);
  },
  /** Seq reads a rules, proxies or groups extension. */
  seq(uid: string): Promise<SeqPatch> {
    return call("Profiles.Seq", uid);
  },
  /** SetDNSOverride turns the DNS override on or off for a profile. */
  setDNSOverride(uid: string, on: boolean): Promise<void> {
    return call("Profiles.SetDNSOverride", uid, on);
  },
  /** Templates returns the templates of new extensions, by kind. */
  templates(): Promise<Record<string, string>> {
    return call("Profiles.Templates");
  },
  /**
   * Update downloads a remote profile again; withProxy chooses the route
   * (nil: as the profile says, falling back to the proxy).
   */
  update(uid: string, withProxy: boolean | null): Promise<Profile> {
    return call("Profiles.Update", uid, withProxy);
  },
  /** UpdateAll updates every remote profile, and returns those that failed. */
  updateAll(): Promise<Record<string, string>> {
    return call("Profiles.UpdateAll");
  },
} as const;

/** Proxies is the proxies page. */
export const Proxies = {
  /** Delay tests the delay of a proxy, in ms; 0 when it failed. */
  delay(name: string, testURL: string): Promise<number> {
    return call("Proxies.Delay", name, testURL);
  },
  /** GroupDelay tests every member of a group at once. */
  groupDelay(group: string, testURL: string): Promise<Record<string, number>> {
    return call("Proxies.GroupDelay", group, testURL);
  },
  /** HealthcheckProvider tests a provider's proxies. */
  healthcheckProvider(name: string): Promise<void> {
    return call("Proxies.HealthcheckProvider", name);
  },
  /** Select selects a member of a selector group. */
  select(group: string, name: string): Promise<void> {
    return call("Proxies.Select", group, name);
  },
  /** Unfix lets a url-test or fallback group choose again. */
  unfix(group: string): Promise<void> {
    return call("Proxies.Unfix", group);
  },
  /** UpdateProvider downloads a provider again. */
  updateProvider(name: string): Promise<void> {
    return call("Proxies.UpdateProvider", name);
  },
  /**
   * View returns the groups and proxies of the running configuration, in
   * the order of the configuration.
   */
  view(): Promise<ProxiesView> {
    return call("Proxies.View");
  },
} as const;

/** Connections is the connections page. */
export const Connections = {
  /** Close closes connections. */
  close(ids: string[]): Promise<void> {
    return call("Connections.Close", ids);
  },
  /** CloseAll closes every connection. */
  closeAll(): Promise<void> {
    return call("Connections.CloseAll");
  },
  /** Stream sends the open connections every second. */
  stream(ch: Channel<Connections>): Promise<void> {
    return call("Connections.Stream", ch);
  },
} as const;

/** Stats is the traffic statistics page. */
export const Stats = {
  /** Clear forgets the statistics. */
  clear(): Promise<void> {
    return call("Stats.Clear");
  },
  /**
   * Query totals the traffic of a range of days, and ranks its apps, sites
   * and nodes.
   */
  query(q: StatsQuery): Promise<StatsReport> {
    return call("Stats.Query", q);
  },
} as const;

/** Rules is the rules page. */
export const Rules = {
  /**
   * EnableAll enables the rules disabled since the last reload, and returns
   * how many there were.
   */
  enableAll(): Promise<number> {
    return call("Rules.EnableAll");
  },
  /** List returns the running rules and rule providers. */
  list(): Promise<RulesView> {
    return call("Rules.List");
  },
  /** SetDisabled disables or enables a rule until the next reload. */
  setDisabled(index: number, disabled: boolean): Promise<void> {
    return call("Rules.SetDisabled", index, disabled);
  },
  /** UpdateProvider downloads a rule provider again. */
  updateProvider(name: string): Promise<void> {
    return call("Rules.UpdateProvider", name);
  },
} as const;

/** Logs is the logs page. */
export const Logs = {
  /** Clear forgets the logs kept. */
  clear(): Promise<void> {
    return call("Logs.Clear");
  },
  /**
   * Export saves logs, as the page shows them, to a file the user picks, and
   * returns its path, "" when cancelled.
   */
  export(text: string): Promise<string> {
    return call("Logs.Export", text);
  },
  /** Recent returns the logs kept, oldest first. */
  recent(): Promise<LogEvent[]> {
    return call("Logs.Recent");
  },
  /** Stream sends new logs as they come. */
  stream(ch: Channel<LogEvent>): Promise<void> {
    return call("Logs.Stream", ch);
  },
} as const;

/** Core is the core itself. */
export const Core = {
  /** DNSQuery resolves a name with the core's DNS. */
  dnsQuery(name: string, typ: string): Promise<DNSQueryResult> {
    return call("Core.DNSQuery", name, typ);
  },
  /** FlushDNS empties the DNS cache. */
  flushDNS(): Promise<void> {
    return call("Core.FlushDNS");
  },
  /** FlushFakeIP empties the fake-ip cache. */
  flushFakeIP(): Promise<void> {
    return call("Core.FlushFakeIP");
  },
  /** Memory sends the core's memory use every second. */
  memory(ch: Channel<Memory>): Promise<void> {
    return call("Core.Memory", ch);
  },
  /** OpenWebUI opens a dashboard in the browser. */
  openWebUI(template: string): Promise<void> {
    return call("Core.OpenWebUI", template);
  },
  /**
   * PortInUse reports whether a TCP port of the loopback is taken by
   * another program.
   */
  portInUse(port: number): Promise<boolean> {
    return call("Core.PortInUse", port);
  },
  /** Reapply generates and applies the configuration again. */
  reapply(): Promise<void> {
    return call("Core.Reapply");
  },
  /** Restart restarts the core. */
  restart(): Promise<void> {
    return call("Core.Restart");
  },
  /** SetMode switches the mode: rule, global or direct. */
  setMode(mode: string): Promise<void> {
    return call("Core.SetMode", mode);
  },
  /** Traffic sends the traffic every second. */
  traffic(ch: Channel<Traffic>): Promise<void> {
    return call("Core.Traffic", ch);
  },
  /** UpdateGeo downloads the GeoIP, GeoSite and ASN databases again. */
  updateGeo(): Promise<void> {
    return call("Core.UpdateGeo");
  },
  /**
   * WebUIURL fills a dashboard's URL with the controller's host, port and
   * secret.
   */
  webUIURL(template: string): Promise<string> {
    return call("Core.WebUIURL", template);
  },
} as const;

/** System is what touches the operating system: the service. */
export const System = {
  /**
   * InstallService installs (or repairs, or updates) the service, asking for
   * an administrator's authorization, and moves the core to it; with
   * enableTun, it then turns TUN mode on.
   */
  installService(enableTun: boolean): Promise<void> {
    return call("System.InstallService", enableTun);
  },
  /** ServiceStatus checks the service. */
  serviceStatus(): Promise<ServiceState> {
    return call("System.ServiceStatus");
  },
  /**
   * SetUWPLoopback lets the Store apps of sids, among those UWPApps lists,
   * reach the proxy, and no others of them; it asks for an administrator.
   */
  setUWPLoopback(sids: string[]): Promise<void> {
    return call("System.SetUWPLoopback", sids);
  },
  /**
   * UWPApps lists the Windows Store apps, and which may reach the proxy on
   * the loopback.
   */
  uwpApps(): Promise<StoreApp[]> {
    return call("System.UWPApps");
  },
  /**
   * UninstallService removes the service; the core moves back to the app,
   * without TUN.
   */
  uninstallService(): Promise<void> {
    return call("System.UninstallService");
  },
} as const;

/** Tailscale is the tailnet page. */
export const Tailscale = {
  /**
   * Login logs the embedded node in: with an auth key, or interactively, in
   * which case it returns the URL to open.
   */
  login(authKey: string): Promise<string> {
    return call("Tailscale.Login", authKey);
  },
  /**
   * Logout logs the embedded node out; forget also deletes its identity, so
   * that the next login makes a new device.
   */
  logout(forget: boolean): Promise<void> {
    return call("Tailscale.Logout", forget);
  },
  /** OpenAdmin opens the tailnet's admin console. */
  openAdmin(): Promise<void> {
    return call("Tailscale.OpenAdmin");
  },
  /** Ping pings a peer. */
  ping(ip: string): Promise<TailscalePingResult> {
    return call("Tailscale.Ping", ip);
  },
  /** SetExitNode sends traffic to the internet through a peer ("" for none). */
  setExitNode(target: string): Promise<void> {
    return call("Tailscale.SetExitNode", target);
  },
  /** SetPrefs changes the node's preferences. */
  setPrefs(p: TailscalePrefs): Promise<void> {
    return call("Tailscale.SetPrefs", p);
  },
  /** SetRunning connects or disconnects the installed Tailscale app. */
  setRunning(on: boolean): Promise<void> {
    return call("Tailscale.SetRunning", on);
  },
  /**
   * Status returns the tailnet's status: the embedded node's, or the
   * installed client's.
   */
  status(): Promise<TailscaleStatus> {
    return call("Tailscale.Status");
  },
  /** SystemStatus checks the installed Tailscale app, whatever the mode. */
  systemStatus(): Promise<TailscaleStatus> {
    return call("Tailscale.SystemStatus");
  },
} as const;

/** Sync is the sync and backup page. */
export const Sync = {
  /**
   * Backups lists the backups of the device and, when sync is set up, of the
   * server.
   */
  backups(): Promise<BackupInfo[]> {
    return call("Sync.Backups");
  },
  /** ChangePassphrase wraps the vault's key with a new passphrase. */
  changePassphrase(passphrase: string): Promise<void> {
    return call("Sync.ChangePassphrase", passphrase);
  },
  /** CreateBackup makes a backup on the device, or on the server. */
  createBackup(remote: boolean): Promise<string> {
    return call("Sync.CreateBackup", remote);
  },
  /** DeleteBackup deletes a backup. */
  deleteBackup(name: string, remote: boolean): Promise<void> {
    return call("Sync.DeleteBackup", name, remote);
  },
  /** Devices lists the devices that sync with the vault. */
  devices(): Promise<DeviceInfo[]> {
    return call("Sync.Devices");
  },
  /**
   * Disable turns sync off; forget also deletes the saved credentials and
   * keys from this device. The server keeps its data.
   */
  disable(forget: boolean): Promise<void> {
    return call("Sync.Disable", forget);
  },
  /**
   * ExportBackup saves a backup to a file the user picks, encrypted with a
   * password of their choice.
   */
  exportBackup(name: string, remote: boolean, password: string): Promise<string> {
    return call("Sync.ExportBackup", name, remote, password);
  },
  /** ImportBackup restores a file made by ExportBackup. */
  importBackup(password: string): Promise<void> {
    return call("Sync.ImportBackup", password);
  },
  /** Now syncs now. */
  now(): Promise<Report> {
    return call("Sync.Now");
  },
  /** Probe tests a server without changing anything. */
  probe(setup: SyncSetup): Promise<SyncProbe> {
    return call("Sync.Probe", setup);
  },
  /** Resolve resolves a conflict (local, remote or both) and syncs. */
  resolve(path: string, choice: string): Promise<void> {
    return call("Sync.Resolve", path, choice);
  },
  /**
   * RestoreBackup replaces the app's data with a backup's. A backup of the
   * current data is made first.
   */
  restoreBackup(name: string, remote: boolean): Promise<void> {
    return call("Sync.RestoreBackup", name, remote);
  },
  /**
   * Setup connects to the server, opens its vault with the passphrase (or
   * creates it), saves the credentials and turns sync on. It returns whether
   * it created the vault.
   */
  setup(setup: SyncSetup): Promise<boolean> {
    return call("Sync.Setup", setup);
  },
  /** Status returns the state of sync. */
  status(): Promise<SyncStatus> {
    return call("Sync.Status");
  },
} as const;

/** Tools tests the network through the proxy. */
export const Tools = {
  /**
   * CheckUnlock checks services through the proxy, sending each result as it
   * arrives.
   */
  checkUnlock(ids: string[], ch: Channel<Unlock>): Promise<void> {
    return call("Tools.CheckUnlock", ids, ch);
  },
  /** ConnectivitySites returns the sites the connectivity page tests. */
  connectivitySites(): Promise<Site[]> {
    return call("Tools.ConnectivitySites");
  },
  /**
   * ExitIP returns the address that a kind of site sees through the proxy:
   * "domestic" for sites in mainland China, "global" for sites abroad, or
   * "cloudflare".
   */
  exitIP(view: string): Promise<IPInfo> {
    return call("Tools.ExitIP", view);
  },
  /**
   * IPInfo returns the address the world sees, through the proxy, or
   * directly when direct is set.
   */
  ipInfo(direct: boolean): Promise<IPInfo> {
    return call("Tools.IPInfo", direct);
  },
  /** Sites returns the sites the home page tests. */
  sites(): Promise<Site[]> {
    return call("Tools.Sites");
  },
  /**
   * TestSites tests sites through the proxy, sending each result as it
   * arrives.
   */
  testSites(sites: Site[], ch: Channel<SiteResult>): Promise<void> {
    return call("Tools.TestSites", sites, ch);
  },
  /**
   * UnlockList returns the streaming and AI services the connectivity page
   * checks.
   */
  unlockList(): Promise<Unlock[]> {
    return call("Tools.UnlockList");
  },
} as const;

/** UpdateService checks for updates of the app. */
export const Updates = {
  /**
   * Check checks for an update now, in the update window, which also says
   * when the app is up to date or why it cannot update itself.
   */
  check(): Promise<void> {
    return call("Updates.Check");
  },
  /** ReleasesURL returns the page to download versions from. */
  releasesURL(): Promise<string> {
    return call("Updates.ReleasesURL");
  },
  /**
   * SetAutomaticDownloads installs updates found in the background without
   * asking, or not.
   */
  setAutomaticDownloads(on: boolean): Promise<void> {
    return call("Updates.SetAutomaticDownloads", on);
  },
  /** State returns the state of updates. */
  state(): Promise<UpdateState> {
    return call("Updates.State");
  },
} as const;

// ---- Events ----

/** Events sent by the Go side. Subscribe with `events.name.on(listener)`. */
export const events = {
  /** StateEvent is sent whenever the app's state changes. */
  state: event<AppState>("state"),
  /** SettingsEvent is sent when the settings changed. */
  settings: event<Settings>("settings"),
  /** ProfilesEvent is sent when profiles changed. */
  profiles: event<ProfilesView>("profiles"),
  /** NoticeEvent is a message for the user. */
  notice: event<Notice>("notice"),
  /** TailscaleEvent is sent when the tailnet's status changed. */
  tailscale: event<TailscaleStatus>("tailscale"),
  /** SyncEvent is sent when the sync's status changed. */
  sync: event<SyncStatus>("sync"),
  /** NavigateEvent asks the page to show a page: home, proxies, settings... */
  navigate: event<string>("navigate"),
  /**
   * RuntimeEvent is sent after a configuration was applied, when proxies,
   * rules and providers may have changed.
   */
  runtime: event<RuntimeInfo>("runtime"),
  /**
   * SelectionEvent is sent when a group's selection changed outside the
   * page, from the tray or the quick panel.
   */
  selection: event<Selection>("selection"),
  /** UpdateEvent tells pages that UpdateState changed. */
  update: event<UpdateState>("update"),
} as const;
